/*
 * This file was automatically generated by EvoSuite
 * Sun Apr 19 05:30:27 GMT 2026
 */

package comp5111.assignment.cut;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import comp5111.assignment.cut.Subject;
import java.nio.ByteBuffer;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.System;
import org.junit.runner.RunWith;

// @RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Subject_evosuite0_ESTest {

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      Subject subject0 = new Subject();
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("FAem,");
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      Subject subject0 = new Subject();
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("oN");
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration((-319), (Subject.GamePlayer[]) null);
      } catch(IllegalArgumentException e) {
         //
         // size of gameboard must be at least 3
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      Subject subject0 = new Subject();
      Number number0 = Subject.StringAlgorithms.parseNumber("0D");
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      Subject subject0 = new Subject();
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("YeJ");
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      Subject subject0 = new Subject();
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("t:?r");
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      Subject subject0 = new Subject();
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("T");
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("YT ");
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(2, 2);
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("}wFRk'");
      subject_GamePlayer0.setScore(15);
      subject_GamePlayerArray0[0] = subject_GamePlayer0;
      subject_GamePlayerArray0[1] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(15, subject_GamePlayerArray0);
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      boolean boolean0 = subject_GameConfiguration0.isBoardSymmetric();
      Subject.GamePlayer subject_GamePlayer1 = subject0.new GamePlayer();
      List<Subject.GamePlace> list0 = subject_GameConfiguration0.getPlacesOfPlayer(subject_GamePlayer1);
      Subject.GamePlayer subject_GamePlayer2 = subject0.new GamePlayer();
      List<Subject.GamePlace> list1 = subject_GameConfiguration0.getPlacesOfPlayer(subject_GamePlayer2);
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      Subject subject0 = new Subject();
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("n");
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(2, 2);
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("}wFRk'");
      subject_GamePlayer0.setScore(15);
      subject_GamePlayerArray0[0] = subject_GamePlayer0;
      subject_GamePlace0.x(0);
      subject_GamePlayerArray0[1] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(15, subject_GamePlayerArray0);
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      boolean boolean0 = subject_GameConfiguration0.isBoardSymmetric();
      int[] intArray0 = subject_GameConfiguration0.countPiecesPerPlayer();
      boolean boolean1 = subject_GameConfiguration0.isBoardFull();
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      Subject subject0 = new Subject();
      Number number0 = Subject.StringAlgorithms.parseNumber("8l");
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(4, 4);
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayerArray0[1] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(9, subject_GamePlayerArray0);
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      } catch(IllegalArgumentException e) {
         //
         // piece cannot be put at central place initially
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(4, 4);
      subject_GamePlace0.y((-542));
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayerArray0[1] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(15, subject_GamePlayerArray0);
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      } catch(IllegalArgumentException e) {
         //
         // the place(4, -542) must be inside the gameboard
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(4, 4);
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayerArray0[1] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(15, subject_GamePlayerArray0);
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      boolean boolean0 = subject_GameConfiguration0.isBoardSymmetric();
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      Subject subject0 = new Subject();
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("No");
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      Subject subject0 = new Subject();
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("sWms-7/.ro _L* jl");
      } catch(NumberFormatException e) {
         //
         // sWms-7/.ro _L* jl
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      Subject subject0 = new Subject();
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("MDC|7Eh!Z8;Z3e<J{&*6");
      } catch(NumberFormatException e) {
         //
         // For input string: \"MD\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("May");
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(4, 4);
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayerArray0[1] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(15, subject_GamePlayerArray0);
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      String string0 = subject_GameConfiguration0.toString();
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      int[] intArray0 = subject_GameConfiguration0.countPiecesPerPlayer();
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(4, 4);
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayerArray0[1] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(15, subject_GamePlayerArray0);
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      List<Subject.GamePlace> list0 = subject_GameConfiguration0.getPlacesOfPlayer(subject_GamePlayer0);
      int[] intArray0 = subject_GameConfiguration0.countPiecesPerPlayer();
      boolean boolean0 = subject_GameConfiguration0.isBoardFull();
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(4, 4);
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      subject_GamePlace0.y(15);
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayerArray0[1] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(15, subject_GamePlayerArray0);
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      } catch(IllegalArgumentException e) {
         //
         // the place(4, 15) must be inside the gameboard
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(4, 4);
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayerArray0[0] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(15, subject_GamePlayerArray0);
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      int[] intArray0 = subject_GameConfiguration0.countPiecesPerPlayer();
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(4, 4);
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayerArray0[1] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(15, subject_GamePlayerArray0);
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      int[] intArray0 = subject_GameConfiguration0.countPiecesPerPlayer();
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      Subject subject0 = new Subject();
      Number number0 = Subject.StringAlgorithms.parseNumber("-0l");
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(4, 4);
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayerArray0[1] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(15, subject_GamePlayerArray0);
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      List<Subject.GamePlace> list0 = subject_GameConfiguration0.getEmptyPlaces();
      int[] intArray0 = subject_GameConfiguration0.countPiecesPerPlayer();
      boolean boolean0 = subject_GameConfiguration0.isBoardFull();
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
      Subject subject0 = new Subject();
      List<String> list0 = Subject.DateTimeAlgorithms.listDatesBetween(2010, 3, 3, 3, 3, 3);
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(10, 10);
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("}wFRk'");
      subject_GamePlayer0.resetScore();
      subject_GamePlayerArray0[1] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(15, subject_GamePlayerArray0);
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      int[] intArray0 = subject_GameConfiguration0.countPiecesPerPlayer();
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("N");
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("yCO");
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(16, 16);
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayerArray0[1] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(9, subject_GamePlayerArray0);
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      } catch(IllegalArgumentException e) {
         //
         // the place(16, 16) must be inside the gameboard
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      Subject subject0 = new Subject();
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("MDDi7E!Z8;Z3e.{&*6");
      } catch(NumberFormatException e) {
         //
         // Character M is neither a decimal digit number, decimal point, nor \"e\" notation exponential mark.
         //
         verifyException("java.math.BigDecimal", e);
      }
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      Subject subject0 = new Subject();
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("Tq f");
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      Subject subject0 = new Subject();
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("FGepM");
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("!YLpD");
      } catch(NumberFormatException e) {
         //
         // Character ! is neither a decimal digit number, decimal point, nor \"e\" notation exponential mark.
         //
         verifyException("java.math.BigDecimal", e);
      }
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("t");
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      Subject subject0 = new Subject();
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("fl&^X");
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("y");
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("o0");
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("OD");
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("7E3");
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      Subject subject0 = new Subject();
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("F");
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      Subject subject0 = new Subject();
      boolean boolean0 = Subject.DateTimeAlgorithms.judgeLeapYear(700);
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      Subject subject0 = new Subject();
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Mar");
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("Tq f");
      } catch(NumberFormatException e) {
      }
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      Subject subject0 = new Subject();
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("d\"zheG4k_]iL");
      } catch(NumberFormatException e) {
         //
         // d\"zheG4k_]iL
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      Subject subject0 = new Subject();
      Number number0 = Subject.StringAlgorithms.parseNumber("5");
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      Subject subject0 = new Subject();
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("Jan");
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Jan");
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      String string0 = Subject.DateTimeAlgorithms.lastDayOfMonth((-1033), (-1318));
      byte[] byteArray0 = new byte[1];
      byteArray0[0] = (byte)111;
      ByteBuffer byteBuffer0 = ByteBuffer.wrap(byteArray0);
      ByteBuffer byteBuffer1 = ByteBuffer.wrap(byteArray0);
      int int0 = byteBuffer0.mismatch(byteBuffer1);
      StringBuilder stringBuilder0 = new StringBuilder((CharSequence) "(invalid)");
      int int1 = Subject.StringAlgorithms.decodeOctets((byte)111, byteBuffer0, stringBuilder0);
      Subject subject1 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(116, 1424);
      Subject subject2 = new Subject();
      Subject subject3 = new Subject();
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Oct");
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(2, 2);
      subject_GamePlace0.y((-701));
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1, 3);
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
      } catch(IllegalArgumentException e) {
         //
         // Place is out of bounds
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 0);
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
      subject_GamePlace1.y((-1));
      boolean boolean0 = subject_GamePlace0.isAdjacent(subject_GamePlace1);
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      Subject subject0 = new Subject();
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("Jul");
      } catch(NumberFormatException e) {
         //
         // Jul
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("-l");
      } catch(NumberFormatException e) {
         //
         // -l
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      Subject subject0 = new Subject();
      byte byte0 = (byte) (-1);
      Subject subject1 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo(".`r}ZLDSYS&S)!As");
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject1.new GameConfiguration(0);
      } catch(IllegalArgumentException e) {
         //
         // size of gameboard must be at least 3
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      Subject subject0 = new Subject();
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("n0");
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      Subject subject0 = new Subject();
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("N:");
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      byteArray0[0] = (byte) (-96);
      ByteBuffer byteBuffer0 = ByteBuffer.wrap(byteArray0);
      String string0 = Subject.DateTimeAlgorithms.lastDayOfMonth((byte) (-96), 70);
      int int0 = byteBuffer0.mismatch(byteBuffer0);
      StringBuilder stringBuilder0 = new StringBuilder((CharSequence) "(invalid)");
      int int1 = Subject.StringAlgorithms.decodeOctets(70, byteBuffer0, stringBuilder0);
      Subject subject0 = new Subject();
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 0);
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
      subject_GamePlace1.x((-1468));
      boolean boolean0 = subject_GamePlace1.equals(subject_GamePlace0);
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject subject1 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject1.new GameConfiguration(7);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1, (-1994900007));
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
      } catch(IllegalArgumentException e) {
         //
         // Place is out of bounds
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject subject1 = new Subject();
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Apr");
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject subject1 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject1.new GameConfiguration(7);
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo((String) null);
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr((-1994900007));
      System.setCurrentTimeMillis(1);
      int int0 = subject_GameConfiguration0.getSize();
      boolean boolean0 = subject_GameConfiguration0.isBoardFull();
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("B'wF1F");
      } catch(NumberFormatException e) {
      }
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      Subject subject0 = new Subject();
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("n0");
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean((String) null, (String) null, "", "");
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      Subject subject0 = new Subject();
      // Undeclared exception!
      Subject.DateTimeAlgorithms.listDatesBetween(9, 9, 9, 9, 9, 9);
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("A(sJEZ[94.}2%>B{T");
      } catch(NumberFormatException e) {
         //
         // A(sJEZ[94.}2%>B{T
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("O<cle");
      } catch(NumberFormatException e) {
         //
         // O<cle
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Jul");
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      Subject subject0 = new Subject();
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("Y");
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      Subject subject0 = new Subject();
      int int0 = Subject.StringAlgorithms.extractIntInStr("5");
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.firstDayOfMonth(11, 7);
      String string1 = Subject.DateTimeAlgorithms.month2MonAbbr(11);
      int int0 = Subject.DateTimeAlgorithms.getQuarter(11);
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("0x");
      } catch(NumberFormatException e) {
         //
         // For input string: \"\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(1740);
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("(invalid)");
      String string1 = Subject.DateTimeAlgorithms.roundSecondToString(1048L);
      int int0 = Subject.DateTimeAlgorithms.getQuarter(6);
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("(invalid)");
      } catch(NumberFormatException e) {
         //
         // (invalid)
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("%04d-%02d-%02d");
      } catch(NumberFormatException e) {
         //
         // Character % is neither a decimal digit number, decimal point, nor \"e\" notation exponential mark.
         //
         verifyException("java.math.BigDecimal", e);
      }
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      Subject subject0 = new Subject();
      // Undeclared exception!
      Subject.DateTimeAlgorithms.listDatesBetween(6, 6, 6, 6, 6, 6);
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("-0xI!K");
      } catch(NumberFormatException e) {
         //
         // For input string: \"-I!K\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("of]");
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("comp5111.assignment.cut.Subject$GamePlayer");
      } catch(NumberFormatException e) {
         //
         // comp5111.assignment.cut.Subject$GamePlayer
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("i.@^.8 Ova=|#");
      } catch(NumberFormatException e) {
         //
         // i.@^.8 Ova=|#
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      List<String> list0 = Subject.DateTimeAlgorithms.listDatesBetween(13, 1, 13, 1, 13, 1);
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("");
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      Subject.GamePlayer subject_GamePlayer1 = subject0.new GamePlayer("");
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("");
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(2145242015, (-924));
      int int0 = subject_GamePlace0.manhattanDistance((Subject.GamePlace) null);
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration((-1));
      } catch(IllegalArgumentException e) {
         //
         // size of gameboard must be at least 3
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      Subject subject0 = new Subject();
      // Undeclared exception!
      Subject.DateTimeAlgorithms.listDatesBetween(10, 10, 10, 10, 10, 10);
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("*b^,nwbH4");
      } catch(NumberFormatException e) {
         //
         // For input string: \"\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      Subject subject0 = new Subject();
      int int0 = Subject.DateTimeAlgorithms.monthsBetween(7, 7, 7, 7);
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7);
      String string0 = Subject.DateTimeAlgorithms.lastDayOfMonth(0, 7);
      Subject.GamePlayer subject_GamePlayer1 = subject0.new GamePlayer();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 79);
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
      Subject.GamePlayer[][] subject_GamePlayerArray0 = subject_GameConfiguration0.getInitialBoard();
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(5);
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDateStrings("u", "&o|`0~ja");
      int int1 = Subject.DateTimeAlgorithms.monthsBetween(5, 5, Integer.MIN_VALUE, (-204));
      int int2 = Subject.DateTimeAlgorithms.monthsBetween((-137), 0, Integer.MIN_VALUE, 0);
      boolean boolean0 = Subject.DateTimeAlgorithms.judgeLeapYear(18);
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      Subject subject0 = new Subject();
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDateStrings("--AC", ".HR!7I>8}g/}=");
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber((String) null);
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("oFJ");
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("OD9");
      Subject subject0 = new Subject();
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      Subject subject0 = new Subject();
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDateStrings("--*gA.mp", "--*gA.mp");
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.lastDayOfMonth(0, 0);
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 0);
      int int0 = subject_GamePlace0.x();
      int int1 = Subject.DateTimeAlgorithms.monAbbr2month("(invalid)");
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("(invalid)", "(invalid)", "(invalid)", "(invalid)");
      int int2 = Subject.DateTimeAlgorithms.daysBetweenDateStrings("\n", "(invalid)");
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(9);
      Subject.GameConfiguration subject_GameConfiguration1 = subject_GameConfiguration0.clone();
      subject_GameConfiguration1.clearInitialBoard();
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(9);
      System.setCurrentTimeMillis(9);
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7);
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(2);
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("Feb");
      } catch(NumberFormatException e) {
         //
         // Feb
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      Subject subject0 = new Subject();
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Feb");
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      Subject subject0 = new Subject();
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(8);
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("Aug");
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      boolean boolean0 = subject_GameConfiguration0.isBoardFull();
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      Subject subject0 = new Subject();
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Jun");
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      Subject subject0 = new Subject();
      String string0 = Subject.DateTimeAlgorithms.formatFullDate(11, 11, 11);
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(11);
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      Subject subject0 = new Subject();
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(12);
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("Dec");
      } catch(NumberFormatException e) {
         //
         // Dec
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("OFX");
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-688), (-688));
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
      Subject.GamePlace subject_GamePlace2 = subject_GamePlace1.clone();
      subject_GamePlace1.y(329);
      Object object0 = new Object();
      boolean boolean0 = subject_GamePlace2.equals(subject_GamePlace1);
      Boolean boolean1 = Subject.StringAlgorithms.strToBoolean("W-");
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr((-688));
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      Subject subject0 = new Subject();
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(3600L);
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Nov");
  }

  @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(2, 2);
      Subject.GamePlayer subject_GamePlayer0 = subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.addInitialPiece((Subject.GamePlayer) null, subject_GamePlace0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test105()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer((String) null);
      boolean boolean0 = subject_GamePlayer0.equals((Object) null);
  }

  @Test(timeout = 4000)
  public void test106()  throws Throwable  {
      Subject subject0 = new Subject();
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("f");
  }

  @Test(timeout = 4000)
  public void test107()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7);
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(7, 7);
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      } catch(IllegalArgumentException e) {
         //
         // the player of the piece is unknown
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test108()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      List<Subject.GamePlace> list0 = subject_GameConfiguration0.getPlacesOfPlayer((Subject.GamePlayer) null);
  }

  @Test(timeout = 4000)
  public void test109()  throws Throwable  {
      Subject subject0 = new Subject();
      String string0 = Subject.DateTimeAlgorithms.firstDayOfMonth(1, 3);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1, 3);
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
  }

  @Test(timeout = 4000)
  public void test110()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(2, 2);
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
  }

  @Test(timeout = 4000)
  public void test111()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(86400000L);
  }

  @Test(timeout = 4000)
  public void test112()  throws Throwable  {
      Subject subject0 = new Subject();
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(0);
  }

  @Test(timeout = 4000)
  public void test113()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(3560L);
  }

  @Test(timeout = 4000)
  public void test114()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(86400L);
  }

  @Test(timeout = 4000)
  public void test115()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(604800L);
  }

  @Test(timeout = 4000)
  public void test116()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("-[");
  }

  @Test(timeout = 4000)
  public void test117()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[6];
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("\n");
      subject_GamePlayerArray0[0] = subject_GamePlayer0;
      Subject.GamePlayer subject_GamePlayer1 = subject_GamePlayer0.clone();
      subject_GamePlayerArray0[1] = subject_GamePlayer1;
      Subject.GamePlayer subject_GamePlayer2 = subject0.new GamePlayer("");
      subject_GamePlayerArray0[2] = subject_GamePlayer2;
      Subject.GamePlayer subject_GamePlayer3 = subject0.new GamePlayer((String) null);
      Subject.GamePlayer subject_GamePlayer4 = subject0.new GamePlayer();
      char[] charArray0 = new char[1];
      charArray0[0] = 'o';
      String string0 = Subject.StringAlgorithms.parseToken("oCY%,l8?2%_IFu=ef>", charArray0);
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration('o');
      } catch(IllegalArgumentException e) {
         //
         // size of gameboard is at most 25
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test118()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean(".");
  }

  @Test(timeout = 4000)
  public void test119()  throws Throwable  {
      Subject subject0 = new Subject();
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean((String) null, "-kH,&Q\".Xzb?", (String) null, "-kH,&Q\".Xzb?");
  }

  @Test(timeout = 4000)
  public void test120()  throws Throwable  {
      Subject subject0 = new Subject();
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("Dec", "Dec", "Dec", "Dec");
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Dec");
  }

  @Test(timeout = 4000)
  public void test121()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Jh&");
  }

  @Test(timeout = 4000)
  public void test122()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Aug");
  }

  @Test(timeout = 4000)
  public void test123()  throws Throwable  {
      byte[] byteArray0 = new byte[2];
      ByteBuffer byteBuffer0 = ByteBuffer.wrap(byteArray0);
      Subject subject0 = new Subject();
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("w");
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo("0xNG57:~t>dI}(t|0GLg");
      StringBuilder stringBuilder0 = new StringBuilder("0xNG57:~t>dI}(t|0GLg");
      int int0 = Subject.StringAlgorithms.decodeOctets((-71), byteBuffer0, stringBuilder0);
  }

  @Test(timeout = 4000)
  public void test124()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr(5465521);
  }

  @Test(timeout = 4000)
  public void test125()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      String string0 = subject_GameConfiguration0.toString();
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo("GameConfiguration (size=3)\n. . .\n. . .\n. . .\n");
  }

  @Test(timeout = 4000)
  public void test126()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.firstDayOfMonth(7, 7);
      int int0 = Subject.DateTimeAlgorithms.monthsBetween(7, 7, 2156, 1545);
  }

  @Test(timeout = 4000)
  public void test127()  throws Throwable  {
      Subject subject0 = new Subject();
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(10);
  }

  @Test(timeout = 4000)
  public void test128()  throws Throwable  {
      Subject subject0 = new Subject();
      String string0 = Subject.DateTimeAlgorithms.dayStr(2);
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("2nd");
  }

  @Test(timeout = 4000)
  public void test129()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[6];
      String[] stringArray0 = new String[0];
      String[] stringArray1 = Subject.StringAlgorithms.trimArrayElements(stringArray0);
      Subject subject1 = new Subject();
      Subject subject2 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject2.new GamePlayer();
      int int0 = 11;
      // Undeclared exception!
      try { 
        Subject.DateTimeAlgorithms.daysBetweenDates((-580), 7, 11, (-1278), 1588, (-722));
      } catch(IllegalArgumentException e) {
         //
         // Invalid date
         //
         verifyException("comp5111.assignment.cut.Subject$DateTimeAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test130()  throws Throwable  {
      boolean boolean0 = Subject.StringAlgorithms.startsWithIgnoreCase((String) null, (String) null);
  }

  @Test(timeout = 4000)
  public void test131()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(7, 7);
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
  }

  @Test(timeout = 4000)
  public void test132()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.DateTimeAlgorithms.daysBetweenDates(12, 2, 12, 12, 1073, 2);
      } catch(IllegalArgumentException e) {
         //
         // Invalid date
         //
         verifyException("comp5111.assignment.cut.Subject$DateTimeAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test133()  throws Throwable  {
      Subject subject0 = new Subject();
      // Undeclared exception!
      Subject.DateTimeAlgorithms.listDatesBetween(2, 2, 2, 2, 2, 2);
  }

  @Test(timeout = 4000)
  public void test134()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.strToBoolean((String) null, "\"t*Ox", "\"t*Ox", "\"t*Ox");
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test135()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean((String) null, (String) null, (String) null, (String) null);
  }

  @Test(timeout = 4000)
  public void test136()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("{");
  }

  @Test(timeout = 4000)
  public void test137()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-8), (-8));
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
  }

  @Test(timeout = 4000)
  public void test138()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      boolean boolean0 = subject_GameConfiguration0.isBoardSymmetric();
  }

  @Test(timeout = 4000)
  public void test139()  throws Throwable  {
      Subject subject0 = new Subject();
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(7);
  }

  @Test(timeout = 4000)
  public void test140()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.formatFullDate(1, 1, 1);
  }

  @Test(timeout = 4000)
  public void test141()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      int[] intArray0 = subject_GameConfiguration0.countPiecesPerPlayer();
  }

  @Test(timeout = 4000)
  public void test142()  throws Throwable  {
      Subject subject0 = new Subject();
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDates(9, 9, 9, 9, 9, 9);
  }

  @Test(timeout = 4000)
  public void test143()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("");
      Subject.GamePlayer subject_GamePlayer1 = subject_GamePlayer0.clone();
      Subject subject1 = new Subject();
      String[] stringArray0 = Subject.StringAlgorithms.trimArrayElements((String[]) null);
      Subject subject2 = new Subject();
      Subject.GamePlayer subject_GamePlayer2 = subject0.new GamePlayer("");
      Subject.GamePlayer subject_GamePlayer3 = subject2.new GamePlayer();
      int int0 = 173;
      Subject.GamePlace subject_GamePlace0 = subject1.new GamePlace(173, 173);
      boolean boolean0 = subject_GamePlace0.equals(subject_GamePlayer1);
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration((-301));
      } catch(IllegalArgumentException e) {
         //
         // size of gameboard must be at least 3
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test144()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("Xbx", "Xbx", "Xbx", "Xbx");
      Boolean boolean1 = Subject.StringAlgorithms.strToBoolean("Xbx", "No", "Xbx", "Xbx");
  }

  @Test(timeout = 4000)
  public void test145()  throws Throwable  {
      Subject subject0 = new Subject();
      boolean boolean0 = Subject.StringAlgorithms.startsWithIgnoreCase("0#kLO.v=q'e/M", (String) null);
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
  }

  @Test(timeout = 4000)
  public void test146()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("--May");
  }

  @Test(timeout = 4000)
  public void test147()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      Subject.GamePlayer subject_GamePlayer1 = subject_GamePlayer0.clone();
      boolean boolean0 = subject_GamePlayer1.equals(subject_GamePlayer0);
  }

  @Test(timeout = 4000)
  public void test148()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(3, 3);
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
      } catch(IllegalArgumentException e) {
         //
         // Place is out of bounds
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test149()  throws Throwable  {
      Subject subject0 = new Subject();
      // Undeclared exception!
      Subject.StringAlgorithms.padRight((String) null, (short)24953, '&');
  }

  @Test(timeout = 4000)
  public void test150()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(5);
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("May");
  }

  @Test(timeout = 4000)
  public void test151()  throws Throwable  {
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo((String) null);
  }

  @Test(timeout = 4000)
  public void test152()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(4794, 9);
      subject_GamePlace0.x((-1));
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
      int int0 = subject_GamePlace0.y();
      int int1 = Subject.DateTimeAlgorithms.getQuarter(366);
      Subject.GamePlace subject_GamePlace2 = subject_GamePlace1.clone();
      subject_GamePlace1.y(9);
      int int2 = 25;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(25);
      Subject.GamePlayer[] subject_GamePlayerArray0 = subject_GameConfiguration0.getPlayers();
      Subject.GameConfiguration subject_GameConfiguration1 = null;
      try {
        subject_GameConfiguration1 = subject0.new GameConfiguration(318);
      } catch(IllegalArgumentException e) {
         //
         // size of gameboard must be an odd number
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test153()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("");
      Subject.GamePlayer subject_GamePlayer1 = subject_GamePlayer0.clone();
      String string0 = Subject.StringAlgorithms.parseToken("", (char[]) null);
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDateStrings("',I~&", "");
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[4];
      subject_GamePlayerArray0[0] = subject_GamePlayer1;
      subject_GamePlayerArray0[1] = subject_GamePlayer0;
      subject_GamePlayerArray0[2] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(Integer.MIN_VALUE);
      } catch(IllegalArgumentException e) {
         //
         // size of gameboard must be at least 3
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test154()  throws Throwable  {
      Subject subject0 = new Subject();
      int int0 = Subject.DateTimeAlgorithms.monthsBetween(7, 7, 7, 7);
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7);
      Subject.GameConfiguration subject_GameConfiguration1 = subject_GameConfiguration0.clone();
      String string0 = Subject.DateTimeAlgorithms.lastDayOfMonth(0, 7);
      Subject.GamePlayer subject_GamePlayer1 = subject0.new GamePlayer();
      Subject.GameConfiguration subject_GameConfiguration2 = subject_GameConfiguration1.clone();
      Subject subject1 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject1.new GamePlace(249, 249);
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
      char[] charArray0 = new char[1];
      String string1 = Subject.StringAlgorithms.parseToken("0000-07-31", charArray0);
  }

  @Test(timeout = 4000)
  public void test155()  throws Throwable  {
      int int0 = Subject.StringAlgorithms.extractIntInStr("0xOD");
  }

  @Test(timeout = 4000)
  public void test156()  throws Throwable  {
      Subject subject0 = new Subject();
      String string0 = Subject.DateTimeAlgorithms.dayStr(3);
  }

  @Test(timeout = 4000)
  public void test157()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(3);
  }

  @Test(timeout = 4000)
  public void test158()  throws Throwable  {
      Subject subject0 = new Subject();
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("the player of the piece is unknown");
      List<String> list0 = Subject.DateTimeAlgorithms.listDatesBetween(142, (-1), 254, 254, 1, 3838);
      String string0 = Subject.StringAlgorithms.padLeft("lz>]{?V'#y&D&AAw", (short)1, 'q');
  }

  @Test(timeout = 4000)
  public void test159()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean((String) null);
  }

  @Test(timeout = 4000)
  public void test160()  throws Throwable  {
      Subject subject0 = new Subject();
      boolean boolean0 = Subject.StringAlgorithms.startsWithIgnoreCase("", "Dec");
      Subject subject1 = new Subject();
  }

  @Test(timeout = 4000)
  public void test161()  throws Throwable  {
      List<String> list0 = Subject.DateTimeAlgorithms.listDatesBetween(76, 1, 76, 1, 1, 1);
  }

  @Test(timeout = 4000)
  public void test162()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7);
      Subject.GameConfiguration subject_GameConfiguration1 = subject_GameConfiguration0.clone();
  }

  @Test(timeout = 4000)
  public void test163()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 0);
      boolean boolean0 = subject_GamePlace0.equals(subject_GamePlace0);
      String string0 = Subject.DateTimeAlgorithms.firstDayOfMonth(0, 0);
      System.setCurrentTimeMillis(0);
  }

  @Test(timeout = 4000)
  public void test164()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(23);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-3137), (-3137));
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
      } catch(IllegalArgumentException e) {
         //
         // Place is out of bounds
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test165()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[0];
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(15, subject_GamePlayerArray0);
      } catch(IllegalArgumentException e) {
         //
         // there must be exactly two players
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test166()  throws Throwable  {
      int int0 = Subject.StringAlgorithms.extractIntInStr((String) null);
  }

  @Test(timeout = 4000)
  public void test167()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(78, 1776);
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
      int int0 = subject_GamePlace1.manhattanDistance(subject_GamePlace0);
  }

  @Test(timeout = 4000)
  public void test168()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1742, 325);
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      Subject.GamePlayer subject_GamePlayer1 = subject_GamePlayer0.clone();
      byte[] byteArray0 = new byte[7];
      byteArray0[0] = (byte)110;
      byteArray0[1] = (byte)5;
      byteArray0[2] = (byte)110;
      byteArray0[3] = (byte)51;
      byteArray0[4] = (byte)51;
      byteArray0[5] = (byte)110;
      byteArray0[6] = (byte)110;
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.enlarge(2643, byteArray0, 325);
      } catch(ArrayIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test169()  throws Throwable  {
      byte[] byteArray0 = new byte[11];
      ByteBuffer byteBuffer0 = ByteBuffer.wrap(byteArray0);
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("o;`");
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr((byte)0);
      String string1 = Subject.DateTimeAlgorithms.month2MonAbbr(25);
      boolean boolean1 = Subject.StringAlgorithms.startsWithIgnoreCase("(invalid)", "o;`");
  }

  @Test(timeout = 4000)
  public void test170()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[6];
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer((String) null);
      subject_GamePlayer0.resetScore();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(909, 909);
      subject_GamePlace0.x(7);
      Subject.GamePlace subject_GamePlace1 = subject0.new GamePlace(909, 5739);
      String string0 = Subject.StringAlgorithms.padLeft((String) null, (short) (-29160), ')');
  }

  @Test(timeout = 4000)
  public void test171()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("/Ts");
  }

  @Test(timeout = 4000)
  public void test172()  throws Throwable  {
      Subject subject0 = new Subject();
      // Undeclared exception!
      Subject.DateTimeAlgorithms.listDatesBetween(4, 4, 4, 4, 4, 4);
  }

  @Test(timeout = 4000)
  public void test173()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-9), (-9));
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayerArray0[1] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(15, subject_GamePlayerArray0);
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      } catch(IllegalArgumentException e) {
         //
         // the place(-9, -9) must be inside the gameboard
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test174()  throws Throwable  {
      int int0 = Subject.StringAlgorithms.extractIntInStr("-0xOD");
  }

  @Test(timeout = 4000)
  public void test175()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject subject1 = new Subject();
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(4);
  }

  @Test(timeout = 4000)
  public void test176()  throws Throwable  {
      boolean boolean0 = Subject.DateTimeAlgorithms.judgeLeapYear(1);
      String string0 = Subject.StringAlgorithms.padRight("tw0r`6r={m", (short)8, '4');
      Subject subject0 = new Subject();
      // Undeclared exception!
      Subject.DateTimeAlgorithms.listDatesBetween(386, (short)8, 1, (short)8, (short)8, (short)8);
  }

  @Test(timeout = 4000)
  public void test177()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject subject1 = new Subject();
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo("");
      System.setCurrentTimeMillis(2802L);
  }

  @Test(timeout = 4000)
  public void test178()  throws Throwable  {
      String[] stringArray0 = new String[1];
      String[] stringArray1 = Subject.StringAlgorithms.trimArrayElements(stringArray0);
      Subject subject0 = new Subject();
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean((String) null);
      Subject subject1 = new Subject();
      Subject subject2 = new Subject();
      Subject subject3 = new Subject();
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("");
  }

  @Test(timeout = 4000)
  public void test179()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.firstDayOfMonth(38, 38);
  }

  @Test(timeout = 4000)
  public void test180()  throws Throwable  {
      Subject subject0 = new Subject();
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.strToBoolean("5", "", "", "");
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test181()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("x8", "+in4v/iDek", "+in4v/iDek", "x8");
  }

  @Test(timeout = 4000)
  public void test182()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(1);
      Object object0 = new Object();
      Subject subject0 = new Subject();
      Subject subject1 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject1.new GamePlace(1, (-1));
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
  }

  @Test(timeout = 4000)
  public void test183()  throws Throwable  {
      Subject subject0 = new Subject();
      int int0 = Subject.DateTimeAlgorithms.getQuarter(9);
  }

  @Test(timeout = 4000)
  public void test184()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean(" ", " ", " ", " ");
  }

  @Test(timeout = 4000)
  public void test185()  throws Throwable  {
      List<String> list0 = Subject.DateTimeAlgorithms.listDatesBetween(0, 1, 0, 1, 1, 1);
  }

  @Test(timeout = 4000)
  public void test186()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.lastDayOfMonth(7, 7);
  }

  @Test(timeout = 4000)
  public void test187()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.firstDayOfMonth((-10), (-10));
  }

  @Test(timeout = 4000)
  public void test188()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.calcDaysInMonth((-1), 115);
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-1), Integer.MIN_VALUE);
      boolean boolean0 = subject_GamePlace0.isAdjacent((Subject.GamePlace) null);
  }

  @Test(timeout = 4000)
  public void test189()  throws Throwable  {
      Subject subject0 = new Subject();
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Se~");
      int int1 = Subject.DateTimeAlgorithms.monthsBetween((-1), (-1), (-1), (-1));
  }

  @Test(timeout = 4000)
  public void test190()  throws Throwable  {
      Subject.DateTimeAlgorithms subject_DateTimeAlgorithms0 = new Subject.DateTimeAlgorithms();
      String string0 = Subject.DateTimeAlgorithms.dayStr(108);
  }

  @Test(timeout = 4000)
  public void test191()  throws Throwable  {
      Subject subject0 = new Subject();
      int int0 = 0;
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 0);
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
      boolean boolean0 = subject_GamePlace1.equals(subject_GamePlace0);
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(0);
      } catch(IllegalArgumentException e) {
         //
         // size of gameboard must be at least 3
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test192()  throws Throwable  {
      Subject subject0 = new Subject();
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("P");
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(3435, 3435);
      boolean boolean1 = subject_GamePlace0.equals("P");
  }

  @Test(timeout = 4000)
  public void test193()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject subject1 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1127, 1127);
      boolean boolean0 = subject_GamePlace0.equals((Object) null);
  }

  @Test(timeout = 4000)
  public void test194()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber(";hynI<<Ol(T2R$");
      } catch(NumberFormatException e) {
         //
         // ;hynI<<Ol(T2R$
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test195()  throws Throwable  {
      List<String> list0 = Subject.DateTimeAlgorithms.listDatesBetween(76, 76, 76, 76, 76, 76);
  }

  @Test(timeout = 4000)
  public void test196()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.formatFullDate((-2249), (-2249), (-2249));
  }

  @Test(timeout = 4000)
  public void test197()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.lastDayOfMonth((-20), (-20));
  }

  @Test(timeout = 4000)
  public void test198()  throws Throwable  {
      String string0 = Subject.StringAlgorithms.padRight("ohyyKGbU>eOSrrhrv~", (short)336, 'Q');
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("v5=l5-R8)2T");
  }

  @Test(timeout = 4000)
  public void test199()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr(5465466);
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Dec");
      int int1 = Subject.DateTimeAlgorithms.daysInYear(12);
  }

  @Test(timeout = 4000)
  public void test200()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("");
      String string0 = subject_GamePlayer0.toString();
  }

  @Test(timeout = 4000)
  public void test201()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-1), (-1));
      subject_GamePlace0.x((-1));
  }

  @Test(timeout = 4000)
  public void test202()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month((String) null);
  }

  @Test(timeout = 4000)
  public void test203()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayer0.resetScore();
  }

  @Test(timeout = 4000)
  public void test204()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(0);
  }

  @Test(timeout = 4000)
  public void test205()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(735);
  }

  @Test(timeout = 4000)
  public void test206()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("P");
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo("P");
  }

  @Test(timeout = 4000)
  public void test207()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(4063);
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("Q[y6E'<'");
      String string0 = subject_GamePlayer0.getName();
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.strToBoolean(",s3^?NMGg&|", (String) null, (String) null, "Q[y6E'<'");
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test208()  throws Throwable  {
      Subject subject0 = new Subject();
      int int0 = Subject.DateTimeAlgorithms.daysInYear(19);
  }

  @Test(timeout = 4000)
  public void test209()  throws Throwable  {
      boolean boolean0 = Subject.DateTimeAlgorithms.judgeLeapYear(763);
  }

  @Test(timeout = 4000)
  public void test210()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.lastDayOfMonth(38, 38);
  }

  @Test(timeout = 4000)
  public void test211()  throws Throwable  {
      String string0 = Subject.StringAlgorithms.padLeft("Dvne\"", (short)336, 'Q');
  }

  @Test(timeout = 4000)
  public void test212()  throws Throwable  {
      Subject subject0 = new Subject();
      int int0 = Subject.StringAlgorithms.extractIntInStr("");
  }

  @Test(timeout = 4000)
  public void test213()  throws Throwable  {
      int int0 = Subject.StringAlgorithms.extractIntInStr("comp5111.assignment.cut.Subject$GamePlace");
  }

  @Test(timeout = 4000)
  public void test214()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("");
      String[] stringArray0 = new String[9];
      stringArray0[0] = "";
      String[] stringArray1 = Subject.StringAlgorithms.trimArrayElements(stringArray0);
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[5];
  }

  @Test(timeout = 4000)
  public void test215()  throws Throwable  {
      String[] stringArray0 = new String[9];
      String[] stringArray1 = Subject.StringAlgorithms.trimArrayElements(stringArray0);
  }

  @Test(timeout = 4000)
  public void test216()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("SwCD$7!Wt2(veHp[s");
      } catch(NumberFormatException e) {
         //
         // SwCD$7!Wt2(veHp[s
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test217()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      boolean boolean0 = subject_GamePlayer0.equals(subject0);
  }

  @Test(timeout = 4000)
  public void test218()  throws Throwable  {
      Subject subject0 = new Subject();
      byte[] byteArray0 = new byte[2];
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.enlarge((-1), byteArray0, (-1));
      } catch(ArrayIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test219()  throws Throwable  {
      Subject subject0 = new Subject();
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(5465521);
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("Vec");
      int int0 = subject_GamePlayer0.getScore();
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(0);
      } catch(IllegalArgumentException e) {
         //
         // size of gameboard must be at least 3
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test220()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayer0.addScore(618);
      Subject.GamePlayer subject_GamePlayer1 = subject_GamePlayer0.clone();
  }

  @Test(timeout = 4000)
  public void test221()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(115, 115);
      boolean boolean0 = subject_GamePlace0.isAdjacent(subject_GamePlace0);
  }

  @Test(timeout = 4000)
  public void test222()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayer0.setScore(3);
      List<Subject.GamePlace> list0 = subject_GameConfiguration0.getPlacesOfPlayer(subject_GamePlayer0);
  }

  @Test(timeout = 4000)
  public void test223()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(115, 115);
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
  }

  @Test(timeout = 4000)
  public void test224()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(38);
  }

  @Test(timeout = 4000)
  public void test225()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(6);
  }

  @Test(timeout = 4000)
  public void test226()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      List<Subject.GamePlace> list0 = subject_GameConfiguration0.getEmptyPlaces();
  }

  @Test(timeout = 4000)
  public void test227()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(2, 2);
      subject_GamePlace0.y((-701));
  }

  @Test(timeout = 4000)
  public void test228()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("");
  }

  @Test(timeout = 4000)
  public void test229()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr(45);
  }

  @Test(timeout = 4000)
  public void test230()  throws Throwable  {
      Subject subject0 = new Subject();
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(25);
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("(invalid)", "(invalid)", "(invalid)", "(invalid)");
      int int0 = Subject.DateTimeAlgorithms.monthsBetween(25, 25, 25, 25);
  }

  @Test(timeout = 4000)
  public void test231()  throws Throwable  {
      boolean boolean0 = Subject.DateTimeAlgorithms.judgeLeapYear(0);
      Subject subject0 = new Subject();
  }

  @Test(timeout = 4000)
  public void test232()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr((-1816));
  }

  @Test(timeout = 4000)
  public void test233()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.formatFullDate(6, 6, 6);
  }

  @Test(timeout = 4000)
  public void test234()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(1970);
      } catch(IllegalArgumentException e) {
         //
         // size of gameboard must be an odd number
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test235()  throws Throwable  {
      Subject.StringAlgorithms subject_StringAlgorithms0 = new Subject.StringAlgorithms();
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration((-2975));
      } catch(IllegalArgumentException e) {
         //
         // size of gameboard must be at least 3
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test236()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monthsBetween(7, 7, 7, 7);
      Subject subject0 = new Subject();
  }

  @Test(timeout = 4000)
  public void test237()  throws Throwable  {
      boolean boolean0 = Subject.DateTimeAlgorithms.judgeLeapYear(2748);
      Subject subject0 = new Subject();
  }

  @Test(timeout = 4000)
  public void test238()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("0x/@)");
  }

  @Test(timeout = 4000)
  public void test239()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration((-184));
      } catch(IllegalArgumentException e) {
         //
         // size of gameboard must be at least 3
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test240()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDateStrings("Dec", "Dec");
      boolean boolean0 = Subject.StringAlgorithms.startsWithIgnoreCase("Dec", "Dec");
      Subject subject0 = new Subject();
  }

  @Test(timeout = 4000)
  public void test241()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("comp5111.assignment.cut.Subject$GamePlace");
  }

  @Test(timeout = 4000)
  public void test242()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDateStrings("!**>N,vn-MhMFb", "!**>N,vn-MhMFb");
  }

  @Test(timeout = 4000)
  public void test243()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.DateTimeAlgorithms.daysBetweenDates(763, 763, 763, 763, 763, 763);
      } catch(IllegalArgumentException e) {
         //
         // Invalid date
         //
         verifyException("comp5111.assignment.cut.Subject$DateTimeAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test244()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.formatFullDate(5465521, 5465521, 5465521);
  }

  @Test(timeout = 4000)
  public void test245()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(3341);
      } catch(IllegalArgumentException e) {
         //
         // size of gameboard is at most 25
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }
}
