/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 18 13:51:30 GMT 2026
 */

package comp5111.assignment.cut;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import comp5111.assignment.cut.Subject;
import java.nio.ByteBuffer;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

//@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Subject_ESTest_Generate_Evosuite0{

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 7);
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertTrue(boolean0);
      assertEquals(7, subject_GamePlace0.y());
      assertEquals(7, subject_GameConfiguration0.getSize());
      assertEquals(0, subject_GamePlace0.x());
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(9);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(295, 295);
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertEquals(9, subject_GameConfiguration0.getSize());
      assertTrue(boolean0);
      assertEquals("(295, 295)", subject_GamePlace0.toString());
      assertEquals(295, subject_GamePlace0.x());
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 7);
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Place is out of bounds
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((byte)83, 65);
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(9);
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Place is out of bounds
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayerArray0[0] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7, subject_GamePlayerArray0);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-1), 7);
      subject_GamePlace0.x(7);
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // the place(7, 7) must be inside the gameboard
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[3];
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(7, subject_GamePlayerArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // there must be exactly two players
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      assertEquals(3, subject_GameConfiguration0.getSize());
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(365, (-304));
      Subject.GamePlace subject_GamePlace1 = subject0.new GamePlace(365, 365);
      int int0 = subject_GamePlace1.manhattanDistance(subject_GamePlace0);
      assertEquals("(365, 365)", subject_GamePlace1.toString());
      assertEquals(669, int0);
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(9, 1417);
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
      subject_GamePlace1.x((-1719));
      int int0 = subject_GamePlace1.manhattanDistance(subject_GamePlace0);
      assertEquals("(-1719, 1417)", subject_GamePlace1.toString());
      assertEquals(1728, int0);
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(6, 880);
      Subject.GamePlace subject_GamePlace1 = subject0.new GamePlace((-1883), 6);
      boolean boolean0 = subject_GamePlace1.isAdjacent(subject_GamePlace0);
      assertFalse(boolean0);
      assertEquals("(-1883, 6)", subject_GamePlace1.toString());
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-2106185884), (-2106185884));
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
      assertEquals((-2106185884), subject_GamePlace1.y());
      
      subject_GamePlace1.y((-1));
      boolean boolean0 = subject_GamePlace0.equals(subject_GamePlace1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-1), (-1));
      Subject.GamePlace subject_GamePlace1 = subject0.new GamePlace(4044, 1533);
      subject_GamePlace1.equals(subject_GamePlace0);
      assertEquals("(4044, 1533)", subject_GamePlace1.toString());
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monthsBetween(10, 1, 1, 4);
      assertEquals((-105), int0);
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monthsBetween(12, 12, 12, 12);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.firstDayOfMonth(12, 12);
      assertEquals("0012-12-01", string0);
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDateStrings("9Y", "9Y");
      assertEquals(Integer.MIN_VALUE, int0);
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("-0x]l,");
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(9);
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(6);
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(3);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr(31);
      assertEquals("31st", string0);
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr(0);
      assertEquals("(invalid)", string0);
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr(7);
      assertEquals("7th", string0);
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(60L);
      assertEquals("1 M", string0);
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(3600L);
      assertEquals("1 H", string0);
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(604795L);
      assertEquals("7 D", string0);
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(604823L);
      assertEquals("1 W", string0);
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      boolean boolean0 = Subject.DateTimeAlgorithms.judgeLeapYear((-1576));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysInYear((-9));
      assertEquals(365, int0);
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.formatFullDate(1757, 12, (-2925));
      assertEquals("(invalid)", string0);
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      String string0 = Subject.StringAlgorithms.padRight("", (short)0, 'J');
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      String string0 = Subject.StringAlgorithms.padLeft("", (short)0, 'f');
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo("22 S");
      assertArrayEquals(new int[] {22, 0, 0, 0}, intArray0);
      assertNotNull(intArray0);
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo("9isziRTEiLPy|[FY");
      assertNotNull(intArray0);
      assertArrayEquals(new int[] {9, 0, 0, 0}, intArray0);
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("pR");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("(i");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("D");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.enlarge(1, byteArray0, (-1));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      boolean boolean0 = Subject.StringAlgorithms.startsWithIgnoreCase(" ", " ");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      Subject.GamePlayer subject_GamePlayer1 = subject_GamePlayer0.clone();
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer1.toString());
      assertNotSame(subject_GamePlayer1, subject_GamePlayer0);
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 0);
      int int0 = subject_GamePlace0.y();
      assertEquals(0, int0);
      assertEquals(0, subject_GamePlace0.x());
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 968);
      int int0 = subject_GamePlace0.x();
      assertEquals("(0, 968)", subject_GamePlace0.toString());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(3000, (-1));
      String string0 = subject_GamePlace0.toString();
      assertEquals("(3000, -1)", string0);
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      byte[] byteArray0 = new byte[6];
      Subject.StringAlgorithms.enlarge((short)1791, byteArray0, 0);
      assertArrayEquals(new byte[] {(byte)0, (byte)0, (byte)0, (byte)0, (byte)0, (byte)0}, byteArray0);
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDateStrings("0000-01-01", "0000-01-01");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(13);
      subject_GameConfiguration0.clearInitialBoard();
      assertEquals(13, subject_GameConfiguration0.getSize());
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayerArray0[0] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7, subject_GamePlayerArray0);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 7);
      subject_GamePlace0.y(0);
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      assertEquals(0, subject_GamePlace0.y());
      
      boolean boolean0 = subject_GameConfiguration0.isBoardFull();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayerArray0[0] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7, subject_GamePlayerArray0);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 7);
      subject_GamePlace0.y(0);
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      assertEquals("(0, 0)", subject_GamePlace0.toString());
      
      List<Subject.GamePlace> list0 = subject_GameConfiguration0.getPlacesOfPlayer(subject_GamePlayer0);
      assertTrue(list0.contains(subject_GamePlace0));
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayerArray0[0] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7, subject_GamePlayerArray0);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 7);
      subject_GamePlace0.x(1);
      subject_GamePlace0.y(0);
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      assertEquals("(1, 0)", subject_GamePlace0.toString());
      
      boolean boolean0 = subject_GameConfiguration0.isBoardSymmetric();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayerArray0[0] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7, subject_GamePlayerArray0);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 7);
      assertEquals(7, subject_GamePlace0.y());
      
      subject_GamePlace0.y(0);
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      boolean boolean0 = subject_GameConfiguration0.isBoardSymmetric();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayerArray0[0] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7, subject_GamePlayerArray0);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 7);
      assertEquals("(0, 7)", subject_GamePlace0.toString());
      
      subject_GamePlace0.y(0);
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      int[] intArray0 = subject_GameConfiguration0.countPiecesPerPlayer();
      assertArrayEquals(new int[] {1, 0}, intArray0);
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayerArray0[0] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7, subject_GamePlayerArray0);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 7);
      assertEquals(7, subject_GamePlace0.y());
      
      subject_GamePlace0.y(0);
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(9, 1422);
      assertEquals("(9, 1422)", subject_GamePlace0.toString());
      
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(13);
      subject_GamePlace0.y(9);
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(25);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 0);
      subject_GamePlace0.y((-1957));
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertEquals((-1957), subject_GamePlace0.y());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(7, 7);
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertEquals(7, subject_GamePlace0.x());
      assertEquals(7, subject_GameConfiguration0.getSize());
      assertEquals(7, subject_GamePlace0.y());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(9, 1422);
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(13);
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertEquals(9, subject_GamePlace0.x());
      assertEquals("(9, 1422)", subject_GamePlace0.toString());
      assertTrue(boolean0);
      assertEquals(1422, subject_GamePlace0.y());
      assertEquals(13, subject_GameConfiguration0.getSize());
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-4), 7);
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertEquals(7, subject_GameConfiguration0.getSize());
      assertTrue(boolean0);
      assertEquals((-4), subject_GamePlace0.x());
      assertEquals("(-4, 7)", subject_GamePlace0.toString());
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayerArray0[0] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7, subject_GamePlayerArray0);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 7);
      subject_GamePlace0.y(0);
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      assertEquals("(0, 0)", subject_GamePlace0.toString());
      
      List<Subject.GamePlace> list0 = subject_GameConfiguration0.getEmptyPlaces();
      assertEquals(47, list0.size());
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7);
      String string0 = subject_GameConfiguration0.toString();
      assertEquals("GameConfiguration (size=7)\n. . . . . . .\n. . . . . . .\n. . . . . . .\n. . . . . . .\n. . . . . . .\n. . . . . . .\n. . . . . . .\n", string0);
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 0);
      subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
      assertEquals(7, subject_GameConfiguration0.getSize());
      assertEquals(0, subject_GamePlace0.x());
      assertEquals(0, subject_GamePlace0.y());
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(17);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, (-771));
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Place is out of bounds
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(7, 7);
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Place is out of bounds
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(9, 1422);
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(13);
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Place is out of bounds
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-881), 1281);
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Place is out of bounds
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7);
      Subject.GamePlayer[][] subject_GamePlayerArray0 = subject_GameConfiguration0.getInitialBoard();
      assertEquals(7, subject_GamePlayerArray0.length);
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayerArray0[0] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7, subject_GamePlayerArray0);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-1), 7);
      subject_GamePlace0.y((-1));
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // the place(-1, -1) must be inside the gameboard
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayerArray0[0] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7, subject_GamePlayerArray0);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(365, 7);
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // the place(365, 7) must be inside the gameboard
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayerArray0[1] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7, subject_GamePlayerArray0);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-201731128), 95);
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // the place(-201731128, 95) must be inside the gameboard
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[0];
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(19, subject_GamePlayerArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // there must be exactly two players
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(2441);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // size of gameboard is at most 25
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(84);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // size of gameboard must be an odd number
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // size of gameboard must be at least 3
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(7, 127);
      int int0 = subject_GamePlace0.manhattanDistance((Subject.GamePlace) null);
      assertEquals("(7, 127)", subject_GamePlace0.toString());
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((byte) (-10), (byte)1);
      subject_GamePlace0.x(0);
      Subject.GamePlace subject_GamePlace1 = subject0.new GamePlace((byte)1, (byte)1);
      boolean boolean0 = subject_GamePlace0.isAdjacent(subject_GamePlace1);
      assertEquals("(0, 1)", subject_GamePlace0.toString());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(Integer.MIN_VALUE, Integer.MIN_VALUE);
      boolean boolean0 = subject_GamePlace0.isAdjacent((Subject.GamePlace) null);
      assertEquals("(-2147483648, -2147483648)", subject_GamePlace0.toString());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 7);
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
      assertEquals(7, subject_GamePlace1.y());
      
      subject_GamePlace1.y(0);
      boolean boolean0 = subject_GamePlace0.equals(subject_GamePlace1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayerArray0[0] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7, subject_GamePlayerArray0);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(3, 7);
      subject_GamePlace0.y(3);
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // piece cannot be put at central place initially
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(135, 4);
      Object object0 = new Object();
      boolean boolean0 = subject_GamePlace0.equals(object0);
      assertFalse(boolean0);
      assertEquals("(135, 4)", subject_GamePlace0.toString());
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1384, 2886);
      boolean boolean0 = subject_GamePlace0.equals((Object) null);
      assertFalse(boolean0);
      assertEquals("(1384, 2886)", subject_GamePlace0.toString());
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 7);
      boolean boolean0 = subject_GamePlace0.equals(subject_GamePlace0);
      assertEquals("(0, 7)", subject_GamePlace0.toString());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayerArray0[0] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7, subject_GamePlayerArray0);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 7);
      assertEquals("(0, 7)", subject_GamePlace0.toString());
      
      subject_GamePlace0.y(0);
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      String string0 = subject_GameConfiguration0.toString();
      assertEquals("GameConfiguration (size=7)\nP . . . . . .\n. . . . . . .\n. . . . . . .\n. . . . . . .\n. . . . . . .\n. . . . . . .\n. . . . . . .\n", string0);
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayerArray0[0] = subject_GamePlayer0;
      Subject.GamePlayer subject_GamePlayer1 = subject0.new GamePlayer("%XM/[MF%~<G");
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7, subject_GamePlayerArray0);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-201731128), 95);
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.addInitialPiece(subject_GamePlayer1, subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // the player of the piece is unknown
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      boolean boolean0 = subject_GamePlayer0.equals((Object) null);
      assertFalse(boolean0);
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      boolean boolean0 = subject_GamePlayer0.equals("D");
      assertFalse(boolean0);
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monthsBetween(0, 1, 1420, 135);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monthsBetween(1298, 4, (-171713487), 0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monthsBetween((-1), 60, (-1), (-395));
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monthsBetween((-1524), Integer.MIN_VALUE, (-1517), (-1524));
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.firstDayOfMonth(365, 365);
      assertEquals("(invalid)", string0);
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.firstDayOfMonth(4, 4);
      assertEquals("0004-04-01", string0);
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.firstDayOfMonth((-2381), (-2381));
      assertEquals("(invalid)", string0);
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      List<String> list0 = Subject.DateTimeAlgorithms.listDatesBetween(3640, 2, 2, 3, 1, 1);
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      // Undeclared exception!
      Subject.DateTimeAlgorithms.listDatesBetween(9, 9, 9, 9, 9, 9);
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      List<String> list0 = Subject.DateTimeAlgorithms.listDatesBetween(0, 4, 4, (-1573), 1777, 277);
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.formatFullDate(3106, (-2111), (-2111));
      assertEquals("(invalid)", string0);
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDateStrings("--Aug", "--Aug");
      assertEquals(Integer.MIN_VALUE, int0);
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDateStrings("%04d-%02d-01", "cbyn1R:");
      assertEquals(Integer.MIN_VALUE, int0);
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDateStrings("---x0", "---x0");
      assertEquals(Integer.MIN_VALUE, int0);
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysInYear(12);
      assertEquals(366, int0);
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysInYear(300);
      assertEquals(365, int0);
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(12);
      assertEquals("Dec", string0);
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.formatFullDate(11, 11, 11);
      assertEquals("11th Nov 11", string0);
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(10);
      assertEquals("Oct", string0);
  }

  @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(9);
      assertEquals("Sep", string0);
  }

  @Test(timeout = 4000)
  public void test105()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(8);
      assertEquals("Aug", string0);
  }

  @Test(timeout = 4000)
  public void test106()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(7);
      assertEquals("Jul", string0);
  }

  @Test(timeout = 4000)
  public void test107()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(6);
      assertEquals("Jun", string0);
  }

  @Test(timeout = 4000)
  public void test108()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(5);
      assertEquals("May", string0);
  }

  @Test(timeout = 4000)
  public void test109()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(4);
      assertEquals("Apr", string0);
  }

  @Test(timeout = 4000)
  public void test110()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(3);
      assertEquals("Mar", string0);
  }

  @Test(timeout = 4000)
  public void test111()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(2);
      assertEquals("Feb", string0);
  }

  @Test(timeout = 4000)
  public void test112()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(300);
      assertEquals("(invalid)", string0);
  }

  @Test(timeout = 4000)
  public void test113()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(1);
      assertEquals("Jan", string0);
  }

  @Test(timeout = 4000)
  public void test114()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("7th");
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test115()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Nov");
      assertEquals(11, int0);
  }

  @Test(timeout = 4000)
  public void test116()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Oct");
      assertEquals(10, int0);
  }

  @Test(timeout = 4000)
  public void test117()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Dec");
      assertEquals(12, int0);
  }

  @Test(timeout = 4000)
  public void test118()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Jul");
      assertEquals(7, int0);
  }

  @Test(timeout = 4000)
  public void test119()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Jun");
      assertEquals(6, int0);
  }

  @Test(timeout = 4000)
  public void test120()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("May");
      assertEquals(5, int0);
  }

  @Test(timeout = 4000)
  public void test121()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Apr");
      assertEquals(4, int0);
  }

  @Test(timeout = 4000)
  public void test122()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Mar");
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test123()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Feb");
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test124()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Jan");
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test125()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("~");
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test126()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Aug");
      assertEquals(8, int0);
  }

  @Test(timeout = 4000)
  public void test127()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month((String) null);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test128()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(12);
      assertEquals(4, int0);
  }

  @Test(timeout = 4000)
  public void test129()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(4);
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test130()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(1);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test131()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(7);
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test132()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(1132);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test133()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter((-12));
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test134()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr((byte)83);
      assertEquals("(invalid)", string0);
  }

  @Test(timeout = 4000)
  public void test135()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr(462);
      assertEquals("(invalid)", string0);
  }

  @Test(timeout = 4000)
  public void test136()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr(13);
      assertEquals("13th", string0);
  }

  @Test(timeout = 4000)
  public void test137()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr((-12));
      assertEquals("(invalid)", string0);
  }

  @Test(timeout = 4000)
  public void test138()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(400);
      assertEquals("7 M", string0);
  }

  @Test(timeout = 4000)
  public void test139()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(3870L);
      assertEquals("1 H", string0);
  }

  @Test(timeout = 4000)
  public void test140()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(86400L);
      assertEquals("1 D", string0);
  }

  @Test(timeout = 4000)
  public void test141()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(604800L);
      assertEquals("1 W", string0);
  }

  @Test(timeout = 4000)
  public void test142()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(86400000L);
      assertEquals("3 Y", string0);
  }

  @Test(timeout = 4000)
  public void test143()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString((-314L));
      assertEquals("-314 S", string0);
  }

  @Test(timeout = 4000)
  public void test144()  throws Throwable  {
      boolean boolean0 = Subject.DateTimeAlgorithms.judgeLeapYear((-1400));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test145()  throws Throwable  {
      List<String> list0 = Subject.DateTimeAlgorithms.listDatesBetween((-982), 479, (-2251), (-2251), 0, (-982));
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test146()  throws Throwable  {
      List<String> list0 = Subject.DateTimeAlgorithms.listDatesBetween(11, 11, 30, 30, 11, 30);
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test147()  throws Throwable  {
      List<String> list0 = Subject.DateTimeAlgorithms.listDatesBetween(6, 6, (-1457), 3929, 6, (-1457));
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test148()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.lastDayOfMonth(0, 2);
      assertEquals("0000-02-29", string0);
  }

  @Test(timeout = 4000)
  public void test149()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.lastDayOfMonth(17, 2);
      assertEquals("0017-02-28", string0);
  }

  @Test(timeout = 4000)
  public void test150()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.calcDaysInMonth(371, 371);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test151()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.lastDayOfMonth(0, 0);
      assertEquals("(invalid)", string0);
  }

  @Test(timeout = 4000)
  public void test152()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.DateTimeAlgorithms.daysBetweenDates(9, 9, 9, 32, 9, 32);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid date
         //
         verifyException("comp5111.assignment.cut.Subject$DateTimeAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test153()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDates(4, 4, 4, 4, 4, 4);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test154()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.DateTimeAlgorithms.daysBetweenDates(1, 1, 0, 1422, 1422, 1422);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid date
         //
         verifyException("comp5111.assignment.cut.Subject$DateTimeAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test155()  throws Throwable  {
      String string0 = Subject.StringAlgorithms.padRight("0x4u", (short)3, 'z');
      assertEquals("0x4u", string0);
  }

  @Test(timeout = 4000)
  public void test156()  throws Throwable  {
      // Undeclared exception!
      Subject.StringAlgorithms.padRight((String) null, (short)24953, 'V');
  }

  @Test(timeout = 4000)
  public void test157()  throws Throwable  {
      String string0 = Subject.StringAlgorithms.padRight("hn", (short)1791, 'A');
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test158()  throws Throwable  {
      String string0 = Subject.StringAlgorithms.padLeft((String) null, (short)4, ':');
      assertEquals("::::", string0);
  }

  @Test(timeout = 4000)
  public void test159()  throws Throwable  {
      String string0 = Subject.StringAlgorithms.padLeft("uV8_u&8", (short) (-49), '^');
      assertEquals("uV8_u&8", string0);
  }

  @Test(timeout = 4000)
  public void test160()  throws Throwable  {
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo(".Yu(eOQY$^|mo~^Iy0");
      assertNull(intArray0);
  }

  @Test(timeout = 4000)
  public void test161()  throws Throwable  {
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo("0xGameConfiguration (size=7)\nP . . . . . .\n. . . . . . .\n. . . . . . .\n. . . . . . .\n. . . . . . .\n. . . . . . .\n. . . . . . .\n");
      assertNull(intArray0);
  }

  @Test(timeout = 4000)
  public void test162()  throws Throwable  {
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo("");
      assertNull(intArray0);
  }

  @Test(timeout = 4000)
  public void test163()  throws Throwable  {
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo((String) null);
      assertNull(intArray0);
  }

  @Test(timeout = 4000)
  public void test164()  throws Throwable  {
      int int0 = Subject.StringAlgorithms.extractIntInStr("!4;>o.i;Kqtj[");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test165()  throws Throwable  {
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo("1");
      assertNotNull(intArray0);
      assertArrayEquals(new int[] {1, 0, 0, 0}, intArray0);
  }

  @Test(timeout = 4000)
  public void test166()  throws Throwable  {
      int int0 = Subject.StringAlgorithms.extractIntInStr("");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test167()  throws Throwable  {
      int int0 = Subject.StringAlgorithms.extractIntInStr((String) null);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test168()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber(".7");
      assertEquals((short)0, number0.shortValue());
  }

  @Test(timeout = 4000)
  public void test169()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("size of gameboard must be at least 3");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // Character array is missing \"e\" notation exponential mark.
         //
         verifyException("java.math.BigDecimal", e);
      }
  }

  @Test(timeout = 4000)
  public void test170()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("5kCqnBe2!mECbo2");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"5kCqnB\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test171()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("fV*dvp6Xi)uQ%;Ia.PD");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // Character f is neither a decimal digit number, decimal point, nor \"e\" notation exponential mark.
         //
         verifyException("java.math.BigDecimal", e);
      }
  }

  @Test(timeout = 4000)
  public void test172()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("W4iZes`%i:d");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // Character W is neither a decimal digit number, decimal point, nor \"e\" notation exponential mark.
         //
         verifyException("java.math.BigDecimal", e);
      }
  }

  @Test(timeout = 4000)
  public void test173()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("ud= F");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
      }
  }

  @Test(timeout = 4000)
  public void test174()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("a0+:Zp~j0rS//f");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
      }
  }

  @Test(timeout = 4000)
  public void test175()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("Invalid date");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // Invalid date
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test176()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("T(Evx$Fg{tVPy:&) vL");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // T(Evx$Fg{tVPy:&) vL
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test177()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber(".Yu(eOQYH^|mo~^I0");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // Character Y is neither a decimal digit number, decimal point, nor \"e\" notation exponential mark.
         //
         verifyException("java.math.BigDecimal", e);
      }
  }

  @Test(timeout = 4000)
  public void test178()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("GamePlayer{name='comp5111.assignment.cut.Subject$GameConfiguration', score=0}");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // GamePlayer{name='comp5111.assignment.cut.Subject$GameConfiguration', score=0}
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test179()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("fV}.l");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // fV}.l
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test180()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("-0x>Bgzm-/WA");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"->Bgzm-/WA\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test181()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("0x0r'z&pI83ie=PXQ9");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"0r'z&pI83ie=PXQ9\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test182()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("--.$x");
      assertNull(number0);
  }

  @Test(timeout = 4000)
  public void test183()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("t");
      assertNull(number0);
  }

  @Test(timeout = 4000)
  public void test184()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("0");
      assertEquals((short)0, number0.shortValue());
  }

  @Test(timeout = 4000)
  public void test185()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("");
      assertNull(number0);
  }

  @Test(timeout = 4000)
  public void test186()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber((String) null);
      assertNull(number0);
  }

  @Test(timeout = 4000)
  public void test187()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("9rXnq%0XZ'L");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // 9rXnq%0XZ'L
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test188()  throws Throwable  {
      char[] charArray0 = new char[1];
      charArray0[0] = '[';
      String string0 = Subject.StringAlgorithms.parseToken("!lX95Ohn]V \"5p[%", charArray0);
      assertEquals("!lX95Ohn]V \"5p[", string0);
  }

  @Test(timeout = 4000)
  public void test189()  throws Throwable  {
      char[] charArray0 = new char[1];
      String string0 = Subject.StringAlgorithms.parseToken("!lX95Ohn]V \"5p[%", charArray0);
      assertEquals("!lX95Ohn]V \"5p[%", string0);
  }

  @Test(timeout = 4000)
  public void test190()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.strToBoolean("Ldnl)NAwoWR~uz>'X?B", "S", "S", "S");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test191()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("PW", "S", "S", "PW");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test192()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("`&G j", "H[", "`&G j", "yN_");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test193()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.strToBoolean((String) null, "j^EQMkNQC=PVji", "j^EQMkNQC=PVji", "j^EQMkNQC=PVji");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test194()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean((String) null, (String) null, (String) null, "Place is out of bounds");
      assertTrue(boolean0);
      assertNotNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test195()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean((String) null, "", "!lX95Ohn]V \"5p[%", (String) null);
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test196()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean((String) null, "Oct", (String) null, "");
      assertFalse(boolean0);
      assertNotNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test197()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean(">Bg", ">Bg", ">Bg", ">Bg");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test198()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("!{#y'");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test199()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("22 S");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test200()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("t.;'");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test201()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("Y.O");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test202()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("y_Q");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test203()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("Oct");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test204()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("o5I");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test205()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("O}");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test206()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("N(");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test207()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("oI");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test208()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("n]");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test209()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("F");
      assertNotNull(boolean0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test210()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("~");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test211()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("n");
      assertNotNull(boolean0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test212()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("T");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test213()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("t");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test214()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("Y");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test215()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("y");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test216()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("N");
      assertNotNull(boolean0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test217()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean((String) null);
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test218()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("fV}.l");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test219()  throws Throwable  {
      byte[] byteArray0 = new byte[5];
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.enlarge(0, byteArray0, (byte) (-57));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test220()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      byteArray0[0] = (byte) (-121);
      ByteBuffer byteBuffer0 = ByteBuffer.wrap(byteArray0);
      StringBuilder stringBuilder0 = new StringBuilder();
      int int0 = Subject.StringAlgorithms.decodeOctets((byte) (-121), byteBuffer0, stringBuilder0);
      assertEquals("\uFFFD", stringBuilder0.toString());
      assertEquals((-119), int0);
  }

  @Test(timeout = 4000)
  public void test221()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      ByteBuffer byteBuffer0 = ByteBuffer.wrap(byteArray0);
      StringBuilder stringBuilder0 = new StringBuilder();
      int int0 = Subject.StringAlgorithms.decodeOctets((byte)0, byteBuffer0, stringBuilder0);
      assertEquals(2, int0);
      assertEquals(1, byteBuffer0.remaining());
  }

  @Test(timeout = 4000)
  public void test222()  throws Throwable  {
      ByteBuffer byteBuffer0 = ByteBuffer.allocateDirect(70);
      StringBuilder stringBuilder0 = new StringBuilder("-0xuq'?bFD@<$i");
      int int0 = Subject.StringAlgorithms.decodeOctets(100, byteBuffer0, stringBuilder0);
      assertEquals("-0xuq'?bFD@<$i\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000", stringBuilder0.toString());
      assertEquals(309, int0);
  }

  @Test(timeout = 4000)
  public void test223()  throws Throwable  {
      String[] stringArray0 = new String[3];
      stringArray0[0] = "--0r'z&pI83ieQ9";
      String[] stringArray1 = Subject.StringAlgorithms.trimArrayElements(stringArray0);
      assertNotSame(stringArray1, stringArray0);
      assertEquals(3, stringArray1.length);
  }

  @Test(timeout = 4000)
  public void test224()  throws Throwable  {
      String[] stringArray0 = new String[0];
      String[] stringArray1 = Subject.StringAlgorithms.trimArrayElements(stringArray0);
      assertEquals(0, stringArray1.length);
  }

  @Test(timeout = 4000)
  public void test225()  throws Throwable  {
      String[] stringArray0 = Subject.StringAlgorithms.trimArrayElements((String[]) null);
      assertEquals(0, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test226()  throws Throwable  {
      boolean boolean0 = Subject.StringAlgorithms.startsWithIgnoreCase("c=/+r*W!(:a&}-", "");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test227()  throws Throwable  {
      boolean boolean0 = Subject.StringAlgorithms.startsWithIgnoreCase("}w", "vxG</VA%jj*80");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test228()  throws Throwable  {
      boolean boolean0 = Subject.StringAlgorithms.startsWithIgnoreCase("`5le", (String) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test229()  throws Throwable  {
      boolean boolean0 = Subject.StringAlgorithms.startsWithIgnoreCase("(invalid)", "UfV");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test230()  throws Throwable  {
      boolean boolean0 = Subject.StringAlgorithms.startsWithIgnoreCase((String) null, (String) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test231()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayer0.addScore((-185));
      assertEquals("GamePlayer{name='Anonymous Player', score=-185}", subject_GamePlayer0.toString());
  }

  @Test(timeout = 4000)
  public void test232()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer((String) null);
      subject_GamePlayer0.resetScore();
      assertEquals(0, subject_GamePlayer0.getScore());
  }

  @Test(timeout = 4000)
  public void test233()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      String string0 = subject_GamePlayer0.getName();
      assertEquals("Anonymous Player", string0);
  }

  @Test(timeout = 4000)
  public void test234()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7);
      Subject.GameConfiguration subject_GameConfiguration1 = subject_GameConfiguration0.clone();
      assertEquals(7, subject_GameConfiguration1.getSize());
      assertNotSame(subject_GameConfiguration1, subject_GameConfiguration0);
  }

  @Test(timeout = 4000)
  public void test235()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayer0.setScore(7);
      assertEquals(7, subject_GamePlayer0.getScore());
  }

  @Test(timeout = 4000)
  public void test236()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      int int0 = subject_GamePlayer0.getScore();
      assertEquals(0, int0);
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
  }

  @Test(timeout = 4000)
  public void test237()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("comp5111.assignment.cut.Subject$GameConfiguration");
      String string0 = subject_GamePlayer0.toString();
      assertEquals("GamePlayer{name='comp5111.assignment.cut.Subject$GameConfiguration', score=0}", string0);
  }

  @Test(timeout = 4000)
  public void test238()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(13);
      int int0 = subject_GameConfiguration0.getSize();
      assertEquals(13, int0);
  }

  @Test(timeout = 4000)
  public void test239()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7);
      subject_GameConfiguration0.getPlayers();
      assertEquals(7, subject_GameConfiguration0.getSize());
  }

  @Test(timeout = 4000)
  public void test240()  throws Throwable  {
      Subject.StringAlgorithms subject_StringAlgorithms0 = new Subject.StringAlgorithms();
  }

  @Test(timeout = 4000)
  public void test241()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayerArray0[0] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7, subject_GamePlayerArray0);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 7);
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // the place(0, 7) must be inside the gameboard
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test242()  throws Throwable  {
      Subject.DateTimeAlgorithms subject_DateTimeAlgorithms0 = new Subject.DateTimeAlgorithms();
  }
}
