/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 18 14:18:36 GMT 2026
 */

package comp5111.assignment.cut;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import comp5111.assignment.cut.Subject;
import java.nio.ByteBuffer;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

//@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Subject_ESTest_Generate_Evosuite2  {

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration((byte)25);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(22, 3831);
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertEquals(25, subject_GameConfiguration0.getSize());
      assertEquals(3831, subject_GamePlace0.y());
      assertEquals(22, subject_GamePlace0.x());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration((byte)19);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1, 1);
      assertEquals(1, subject_GamePlace0.y());
      
      subject_GamePlace0.y(0);
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertEquals(0, subject_GamePlace0.y());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(11);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(2147483645, 8);
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertEquals(2147483645, subject_GamePlace0.x());
      assertEquals(11, subject_GameConfiguration0.getSize());
      assertEquals("(2147483645, 8)", subject_GamePlace0.toString());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 3);
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertEquals(0, subject_GamePlace0.x());
      assertEquals(3, subject_GamePlace0.y());
      assertTrue(boolean0);
      assertEquals(3, subject_GameConfiguration0.getSize());
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 2874);
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Place is out of bounds
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, (-1));
      assertEquals("(0, -1)", subject_GamePlace0.toString());
      
      subject_GamePlace0.y(0);
      subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
      assertEquals(0, subject_GamePlace0.y());
      assertEquals(3, subject_GameConfiguration0.getSize());
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(3, 3);
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Place is out of bounds
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[6];
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(3, subject_GamePlayerArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // there must be exactly two players
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(205, 205);
      Subject.GamePlace subject_GamePlace1 = subject0.new GamePlace((-1609), (-1809));
      int int0 = subject_GamePlace0.manhattanDistance(subject_GamePlace1);
      assertEquals(3828, int0);
      assertEquals("(-1609, -1809)", subject_GamePlace1.toString());
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1, 1);
      Subject.GamePlace subject_GamePlace1 = subject0.new GamePlace(2796, 2796);
      boolean boolean0 = subject_GamePlace0.isAdjacent(subject_GamePlace1);
      assertEquals("(2796, 2796)", subject_GamePlace1.toString());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 0);
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
      subject_GamePlace0.y(69);
      boolean boolean0 = subject_GamePlace1.equals(subject_GamePlace0);
      assertEquals(69, subject_GamePlace0.y());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(7, 7);
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
      subject_GamePlace1.x(668);
      boolean boolean0 = subject_GamePlace0.equals(subject_GamePlace1);
      assertEquals(668, subject_GamePlace1.x());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monthsBetween((-2759), 7, 1117, 1);
      assertEquals(46506, int0);
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.firstDayOfMonth(0, 12);
      assertEquals("0000-12-01", string0);
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDateStrings("---0x", "Ii!#Hj^ a9@h");
      assertEquals(Integer.MIN_VALUE, int0);
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("1 H");
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("[");
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(7);
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(6);
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(3);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(12);
      assertEquals(4, int0);
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr(31);
      assertEquals("31st", string0);
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr(0);
      assertEquals("(invalid)", string0);
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr(11);
      assertEquals("11th", string0);
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(60L);
      assertEquals("1 M", string0);
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(3600L);
      assertEquals("1 H", string0);
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(86400L);
      assertEquals("1 D", string0);
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(4879724);
      assertEquals("8 W", string0);
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      boolean boolean0 = Subject.DateTimeAlgorithms.judgeLeapYear(84);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      boolean boolean0 = Subject.DateTimeAlgorithms.judgeLeapYear((-1519));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.formatFullDate(1, 1, 0);
      assertEquals("(invalid)", string0);
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.lastDayOfMonth(1, 1);
      assertEquals("0001-01-31", string0);
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.DateTimeAlgorithms.daysBetweenDates((-1), 12, 4185, (-1), (-1), (-840));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid date
         //
         verifyException("comp5111.assignment.cut.Subject$DateTimeAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      String string0 = Subject.StringAlgorithms.padRight("", (short)0, '7');
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      String string0 = Subject.StringAlgorithms.padLeft("N;", (short) (-219), 'P');
      assertEquals("N;", string0);
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      int int0 = Subject.StringAlgorithms.extractIntInStr("9/b0`z#S}LK9S3Z73");
      assertEquals(9, int0);
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo("20uq+");
      assertNotNull(intArray0);
      assertArrayEquals(new int[] {20, 0, 0, 0}, intArray0);
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      char[] charArray0 = new char[5];
      charArray0[0] = '1';
      String string0 = Subject.StringAlgorithms.parseToken("-0xn\"v", charArray0);
      assertEquals("-0xn\"v", string0);
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("zL");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("5J");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean(".");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.enlarge(Integer.MIN_VALUE, byteArray0, Integer.MIN_VALUE);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      StringBuilder stringBuilder0 = new StringBuilder();
      ByteBuffer byteBuffer0 = ByteBuffer.allocateDirect((byte)25);
      int int0 = Subject.StringAlgorithms.decodeOctets((byte)25, byteBuffer0, stringBuilder0);
      assertEquals("java.nio.DirectByteBuffer[pos=25 lim=25 cap=25]", byteBuffer0.toString());
      assertEquals(99, int0);
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      byteArray0[0] = (byte) (-90);
      ByteBuffer byteBuffer0 = ByteBuffer.wrap(byteArray0);
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.decodeOctets((byte) (-90), byteBuffer0, (StringBuilder) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("KP8");
      Subject.GamePlayer subject_GamePlayer1 = subject_GamePlayer0.clone();
      assertNotSame(subject_GamePlayer1, subject_GamePlayer0);
      assertEquals("GamePlayer{name='KP8', score=0}", subject_GamePlayer1.toString());
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 4879724);
      int int0 = subject_GamePlace0.y();
      assertEquals(4879724, int0);
      assertEquals("(0, 4879724)", subject_GamePlace0.toString());
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-1), (-1));
      int int0 = subject_GamePlace0.x();
      assertEquals((-1), subject_GamePlace0.y());
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.calcDaysInMonth(1, 0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      ByteBuffer byteBuffer0 = ByteBuffer.wrap(byteArray0);
      StringBuilder stringBuilder0 = new StringBuilder((CharSequence) "20uq+");
      int int0 = Subject.StringAlgorithms.decodeOctets(121, byteBuffer0, stringBuilder0);
      assertEquals("java.nio.HeapByteBuffer[pos=0 lim=1 cap=1]", byteBuffer0.toString());
      assertEquals(123, int0);
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDateStrings("0002-02-28", "0002-02-28");
      assertEquals(Integer.MIN_VALUE, int0);
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7);
      boolean boolean0 = subject_GameConfiguration0.isBoardFull();
      assertEquals(7, subject_GameConfiguration0.getSize());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(11);
      subject_GameConfiguration0.clearInitialBoard();
      assertEquals(11, subject_GameConfiguration0.getSize());
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration((byte)25);
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("0veQYm5y*TS}N=a=");
      subject_GameConfiguration0.getPlacesOfPlayer(subject_GamePlayer0);
      assertEquals(25, subject_GameConfiguration0.getSize());
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(25);
      boolean boolean0 = subject_GameConfiguration0.isBoardSymmetric();
      assertTrue(boolean0);
      assertEquals(25, subject_GameConfiguration0.getSize());
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(9);
      int[] intArray0 = subject_GameConfiguration0.countPiecesPerPlayer();
      assertEquals(9, subject_GameConfiguration0.getSize());
      assertEquals(2, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(13);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1, (-966));
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertEquals(13, subject_GameConfiguration0.getSize());
      assertEquals((-966), subject_GamePlace0.y());
      assertEquals("(1, -966)", subject_GamePlace0.toString());
      assertTrue(boolean0);
      assertEquals(1, subject_GamePlace0.x());
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(7, 7);
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertTrue(boolean0);
      assertEquals(7, subject_GamePlace0.x());
      assertEquals(7, subject_GameConfiguration0.getSize());
      assertEquals("(7, 7)", subject_GamePlace0.toString());
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration((byte)19);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-18), (-18));
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertTrue(boolean0);
      assertEquals("(-18, -18)", subject_GamePlace0.toString());
      assertEquals((-18), subject_GamePlace0.x());
      assertEquals(19, subject_GameConfiguration0.getSize());
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      List<Subject.GamePlace> list0 = subject_GameConfiguration0.getEmptyPlaces();
      assertEquals(8, list0.size());
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(25);
      subject_GameConfiguration0.toString();
      assertEquals(25, subject_GameConfiguration0.getSize());
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(11);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(6, 11);
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Place is out of bounds
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, (-1));
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Place is out of bounds
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(25);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1481, 3);
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Place is out of bounds
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration((byte)25);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-1302), 1);
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Place is out of bounds
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      Subject.GamePlayer[][] subject_GamePlayerArray0 = subject_GameConfiguration0.getInitialBoard();
      assertEquals(3, subject_GameConfiguration0.getSize());
      assertEquals(3, subject_GamePlayerArray0.length);
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[0];
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(5, subject_GamePlayerArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // there must be exactly two players
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(1047);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // size of gameboard is at most 25
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(2182);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // size of gameboard must be an odd number
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration((short) (-1));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // size of gameboard must be at least 3
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(2874, (-1797));
      int int0 = subject_GamePlace0.manhattanDistance((Subject.GamePlace) null);
      assertEquals((-1), int0);
      assertEquals("(2874, -1797)", subject_GamePlace0.toString());
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-12469270), 7);
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
      assertEquals(7, subject_GamePlace1.y());
      
      subject_GamePlace1.y(6);
      boolean boolean0 = subject_GamePlace1.isAdjacent(subject_GamePlace0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-18), (-18));
      boolean boolean0 = subject_GamePlace0.isAdjacent((Subject.GamePlace) null);
      assertEquals("(-18, -18)", subject_GamePlace0.toString());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-18), (-18));
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
      subject_GamePlace1.y((-2765));
      boolean boolean0 = subject_GamePlace0.equals(subject_GamePlace1);
      assertEquals((-2765), subject_GamePlace1.y());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(7, (-1702));
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
      subject_GamePlace0.x((-1));
      boolean boolean0 = subject_GamePlace1.equals(subject_GamePlace0);
      assertEquals("(-1, -1702)", subject_GamePlace0.toString());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 0);
      boolean boolean0 = subject_GamePlace0.equals(subject0);
      assertFalse(boolean0);
      assertEquals("(0, 0)", subject_GamePlace0.toString());
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-18), (-18));
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
      boolean boolean0 = subject_GamePlace0.equals(subject_GamePlace1);
      assertTrue(boolean0);
      assertEquals("(-18, -18)", subject_GamePlace0.toString());
      assertNotSame(subject_GamePlace1, subject_GamePlace0);
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(7, 7);
      boolean boolean0 = subject_GamePlace0.equals(subject_GamePlace0);
      assertEquals("(7, 7)", subject_GamePlace0.toString());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(89, 89);
      boolean boolean0 = subject_GamePlace0.equals((Object) null);
      assertFalse(boolean0);
      assertEquals("(89, 89)", subject_GamePlace0.toString());
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      boolean boolean0 = subject_GamePlayer0.equals(subject0);
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(9);
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, (Subject.GamePlace) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // the player of the piece is unknown
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer((String) null);
      boolean boolean0 = subject_GamePlayer0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monthsBetween(9, 9, 24, 1179);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monthsBetween(0, 1, 0, 0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monthsBetween((-485), 643, (-2831), (-485));
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monthsBetween(12, 12, 12, 12);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monthsBetween((-1), (-383), 15, (-1));
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.firstDayOfMonth(70, 70);
      assertEquals("(invalid)", string0);
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.firstDayOfMonth(6, 6);
      assertEquals("0006-06-01", string0);
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.firstDayOfMonth(0, 0);
      assertEquals("(invalid)", string0);
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      List<String> list0 = Subject.DateTimeAlgorithms.listDatesBetween((-1), (-1), 29, 29, (-1), 29);
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.formatFullDate(2935, 2935, 2935);
      assertEquals("(invalid)", string0);
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDateStrings("--[Hy", "H&:@0");
      assertEquals(Integer.MIN_VALUE, int0);
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDateStrings("`.% !G C&oieS", "`.% !G C&oieS");
      assertEquals(Integer.MIN_VALUE, int0);
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysInYear((-2948));
      assertEquals(366, int0);
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysInYear(11);
      assertEquals(365, int0);
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr((-306834073));
      assertEquals("(invalid)", string0);
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(12);
      assertEquals("Dec", string0);
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(11);
      assertEquals("Nov", string0);
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.formatFullDate(2874, 10, 10);
      assertEquals("10th Oct 2874", string0);
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(8);
      assertEquals("Aug", string0);
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.formatFullDate(7, 7, 7);
      assertEquals("7th Jul 7", string0);
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.formatFullDate(5, 5, 5);
      assertEquals("5th May 5", string0);
  }

  @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.formatFullDate(4, 4, 4);
      assertEquals("4th Apr 4", string0);
  }

  @Test(timeout = 4000)
  public void test105()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(2);
      assertEquals("Feb", string0);
  }

  @Test(timeout = 4000)
  public void test106()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(1);
      assertEquals("Jan", string0);
  }

  @Test(timeout = 4000)
  public void test107()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("j(n");
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test108()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Nov");
      assertEquals(11, int0);
  }

  @Test(timeout = 4000)
  public void test109()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Oct");
      assertEquals(10, int0);
  }

  @Test(timeout = 4000)
  public void test110()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Aug");
      assertEquals(8, int0);
  }

  @Test(timeout = 4000)
  public void test111()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Jul");
      assertEquals(7, int0);
  }

  @Test(timeout = 4000)
  public void test112()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Jun");
      assertEquals(6, int0);
  }

  @Test(timeout = 4000)
  public void test113()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("May");
      assertEquals(5, int0);
  }

  @Test(timeout = 4000)
  public void test114()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Apr");
      assertEquals(4, int0);
  }

  @Test(timeout = 4000)
  public void test115()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Dec");
      assertEquals(12, int0);
  }

  @Test(timeout = 4000)
  public void test116()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Feb");
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test117()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Mar");
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test118()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Jan");
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test119()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("T/8M");
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test120()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month((String) null);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test121()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(9);
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test122()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(4);
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test123()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(1);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test124()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(1484);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test125()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test126()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr((-233408209));
      assertEquals("(invalid)", string0);
  }

  @Test(timeout = 4000)
  public void test127()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.formatFullDate(3, 3, 3);
      assertEquals("3rd Mar 3", string0);
  }

  @Test(timeout = 4000)
  public void test128()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr(1172);
      assertEquals("(invalid)", string0);
  }

  @Test(timeout = 4000)
  public void test129()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr(13);
      assertEquals("13th", string0);
  }

  @Test(timeout = 4000)
  public void test130()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(397L);
      assertEquals("7 M", string0);
  }

  @Test(timeout = 4000)
  public void test131()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(3919L);
      assertEquals("1 H", string0);
  }

  @Test(timeout = 4000)
  public void test132()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(86430L);
      assertEquals("1 D", string0);
  }

  @Test(timeout = 4000)
  public void test133()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(604800L);
      assertEquals("1 W", string0);
  }

  @Test(timeout = 4000)
  public void test134()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(86400000L);
      assertEquals("3 Y", string0);
  }

  @Test(timeout = 4000)
  public void test135()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(0L);
      assertEquals("0 S", string0);
  }

  @Test(timeout = 4000)
  public void test136()  throws Throwable  {
      boolean boolean0 = Subject.DateTimeAlgorithms.judgeLeapYear(100);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test137()  throws Throwable  {
      boolean boolean0 = Subject.DateTimeAlgorithms.judgeLeapYear(0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test138()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.DateTimeAlgorithms.daysBetweenDates((-207), 11, (-137833279), 11, 11, (-207));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid date
         //
         verifyException("comp5111.assignment.cut.Subject$DateTimeAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test139()  throws Throwable  {
      List<String> list0 = Subject.DateTimeAlgorithms.listDatesBetween((-482), 3, 11, (-1), (-482), (-1104));
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test140()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.formatFullDate(9, 9, 9);
      assertEquals("9th Sep 9", string0);
  }

  @Test(timeout = 4000)
  public void test141()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.formatFullDate(6, 6, 6);
      assertEquals("6th Jun 6", string0);
  }

  @Test(timeout = 4000)
  public void test142()  throws Throwable  {
      List<String> list0 = Subject.DateTimeAlgorithms.listDatesBetween(3486, 11, 11, 3486, 11, 11);
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test143()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.lastDayOfMonth(3, 1833);
      assertEquals("(invalid)", string0);
  }

  @Test(timeout = 4000)
  public void test144()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDates(4, 4, 4, 4, 4, 4);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test145()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.DateTimeAlgorithms.daysBetweenDates(Integer.MIN_VALUE, 2, 2, 2, 2, 2509);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid date
         //
         verifyException("comp5111.assignment.cut.Subject$DateTimeAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test146()  throws Throwable  {
      String string0 = Subject.StringAlgorithms.padRight((String) null, (short)29, 'G');
      assertEquals("GGGGGGGGGGGGGGGGGGGGGGGGGGGGG", string0);
  }

  @Test(timeout = 4000)
  public void test147()  throws Throwable  {
      String string0 = Subject.StringAlgorithms.padRight("OFn", (short) (-1), 'r');
      assertEquals("OFn", string0);
  }

  @Test(timeout = 4000)
  public void test148()  throws Throwable  {
      String string0 = Subject.StringAlgorithms.padLeft("3", (short)1, 'j');
      assertEquals("3", string0);
  }

  @Test(timeout = 4000)
  public void test149()  throws Throwable  {
      String string0 = Subject.StringAlgorithms.padLeft((String) null, (short)4135, '}');
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test150()  throws Throwable  {
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo(".+");
      assertNull(intArray0);
  }

  @Test(timeout = 4000)
  public void test151()  throws Throwable  {
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo("GameConfiguration (size=3)\n. . .\n. . .\n. . .\n");
      assertNull(intArray0);
  }

  @Test(timeout = 4000)
  public void test152()  throws Throwable  {
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo("");
      assertNull(intArray0);
  }

  @Test(timeout = 4000)
  public void test153()  throws Throwable  {
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo((String) null);
      assertNull(intArray0);
  }

  @Test(timeout = 4000)
  public void test154()  throws Throwable  {
      int int0 = Subject.StringAlgorithms.extractIntInStr("3");
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test155()  throws Throwable  {
      int int0 = Subject.StringAlgorithms.extractIntInStr("");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test156()  throws Throwable  {
      int int0 = Subject.StringAlgorithms.extractIntInStr((String) null);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test157()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("size of gameboard must be at least 3");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // Character array is missing \"e\" notation exponential mark.
         //
         verifyException("java.math.BigDecimal", e);
      }
  }

  @Test(timeout = 4000)
  public void test158()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("4W%g&pesep`R!QE9a8");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"W%g&pese\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test159()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("6wD");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // Character w is neither a decimal digit number, decimal point, nor \"e\" notation exponential mark.
         //
         verifyException("java.math.BigDecimal", e);
      }
  }

  @Test(timeout = 4000)
  public void test160()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("9d");
      assertEquals((byte)9, number0.byteValue());
  }

  @Test(timeout = 4000)
  public void test161()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("h0|NF");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
      }
  }

  @Test(timeout = 4000)
  public void test162()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("Kf");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
      }
  }

  @Test(timeout = 4000)
  public void test163()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("lsp|%)oZw/R\u0005E");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // lsp|%)oZw/R\u0005E
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test164()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("~E`A%X:[0vqL");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // ~E`A%X:[0vqL
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test165()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("@&YdMi3Jdl}%.eOgg5");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // Character @ is neither a decimal digit number, decimal point, nor \"e\" notation exponential mark.
         //
         verifyException("java.math.BigDecimal", e);
      }
  }

  @Test(timeout = 4000)
  public void test166()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("0veQY0m5y*.TS}N=a=");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // 0veQY0m5y*.TS}N=a=
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test167()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("U<BB(666.L");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // U<BB(666.L
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test168()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("-0x.+c-");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"-.+c-\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test169()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("0x");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test170()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("--#p'^wj");
      assertNull(number0);
  }

  @Test(timeout = 4000)
  public void test171()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("3");
      assertEquals((short)3, number0.shortValue());
  }

  @Test(timeout = 4000)
  public void test172()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber(".");
      assertNull(number0);
  }

  @Test(timeout = 4000)
  public void test173()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("");
      assertNull(number0);
  }

  @Test(timeout = 4000)
  public void test174()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber((String) null);
      assertNull(number0);
  }

  @Test(timeout = 4000)
  public void test175()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("8l");
      assertEquals((short)8, number0.shortValue());
  }

  @Test(timeout = 4000)
  public void test176()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("-wX7l");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // -wX7l
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test177()  throws Throwable  {
      char[] charArray0 = new char[1];
      charArray0[0] = 'I';
      String string0 = Subject.StringAlgorithms.parseToken("I3?_Qx", charArray0);
      assertEquals("I", string0);
  }

  @Test(timeout = 4000)
  public void test178()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("QOL~", "{'O4qk ", "{'O4qk ", "QOL~");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test179()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("-", "3", "-", "-");
      assertFalse(boolean0);
      assertNotNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test180()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("`.% !G C&oieS", "`.% !G C&oieS", "x;o p!s", "x;o p!s");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test181()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.strToBoolean((String) null, "3", "3", "3");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test182()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean((String) null, "Dec", (String) null, "z.~d5;qh");
      assertFalse(boolean0);
      assertNotNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test183()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean((String) null, (String) null, (String) null, "-R'^^z(d5G");
      assertTrue(boolean0);
      assertNotNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test184()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean((String) null, (String) null, (String) null, (String) null);
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test185()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.strToBoolean("B9P9", "Oct", "", ".+c-");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test186()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("Mi,.)");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test187()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("--'3");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test188()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("t#PA");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test189()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("T/8M");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test190()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("Oct");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test191()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("Y%[");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test192()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("OFn");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test193()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("On");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test194()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("ou");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test195()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("N%");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test196()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("nv");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test197()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("OL");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test198()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("F");
      assertNotNull(boolean0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test199()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("f");
      assertNotNull(boolean0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test200()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("N");
      assertNotNull(boolean0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test201()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("n");
      assertNotNull(boolean0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test202()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("T");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test203()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("t");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test204()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("Y");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test205()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("y");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test206()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean((String) null);
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test207()  throws Throwable  {
      byte[] byteArray0 = new byte[7];
      Subject.StringAlgorithms.enlarge(1, byteArray0, (byte)1);
      assertEquals(7, byteArray0.length);
  }

  @Test(timeout = 4000)
  public void test208()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      Subject.StringAlgorithms.enlarge(577, byteArray0, (byte)0);
      assertArrayEquals(new byte[] {(byte)0}, byteArray0);
  }

  @Test(timeout = 4000)
  public void test209()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      byteArray0[0] = (byte) (-128);
      ByteBuffer byteBuffer0 = ByteBuffer.wrap(byteArray0);
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.decodeOctets((byte) (-128), byteBuffer0, (StringBuilder) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test210()  throws Throwable  {
      String[] stringArray0 = new String[2];
      stringArray0[1] = "(invalid)";
      String[] stringArray1 = Subject.StringAlgorithms.trimArrayElements(stringArray0);
      assertEquals(2, stringArray1.length);
      assertNotSame(stringArray1, stringArray0);
  }

  @Test(timeout = 4000)
  public void test211()  throws Throwable  {
      String[] stringArray0 = new String[0];
      String[] stringArray1 = Subject.StringAlgorithms.trimArrayElements(stringArray0);
      assertEquals(0, stringArray1.length);
  }

  @Test(timeout = 4000)
  public void test212()  throws Throwable  {
      String[] stringArray0 = Subject.StringAlgorithms.trimArrayElements((String[]) null);
      assertEquals(0, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test213()  throws Throwable  {
      boolean boolean0 = Subject.StringAlgorithms.startsWithIgnoreCase("V}r4r", "Y");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test214()  throws Throwable  {
      boolean boolean0 = Subject.StringAlgorithms.startsWithIgnoreCase("--|;evv<a)XK=`~ (gd", "--|;evv<a)XK=`~ (gd");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test215()  throws Throwable  {
      boolean boolean0 = Subject.StringAlgorithms.startsWithIgnoreCase(".", "-0x-Mcomp5111.assignment.cut.Subject");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test216()  throws Throwable  {
      boolean boolean0 = Subject.StringAlgorithms.startsWithIgnoreCase("", (String) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test217()  throws Throwable  {
      boolean boolean0 = Subject.StringAlgorithms.startsWithIgnoreCase((String) null, (String) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test218()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayer0.addScore(4288626);
      assertEquals(4288626, subject_GamePlayer0.getScore());
  }

  @Test(timeout = 4000)
  public void test219()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayer0.resetScore();
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
  }

  @Test(timeout = 4000)
  public void test220()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("comp5111.assignment.cut.Subject$GameConfiguration");
      String string0 = subject_GamePlayer0.getName();
      assertEquals("comp5111.assignment.cut.Subject$GameConfiguration", string0);
  }

  @Test(timeout = 4000)
  public void test221()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayer0.setScore((-1060));
      assertEquals((-1060), subject_GamePlayer0.getScore());
  }

  @Test(timeout = 4000)
  public void test222()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      int int0 = subject_GamePlayer0.getScore();
      assertEquals(0, int0);
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
  }

  @Test(timeout = 4000)
  public void test223()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("");
      String string0 = subject_GamePlayer0.toString();
      assertEquals("GamePlayer{name='', score=0}", string0);
  }

  @Test(timeout = 4000)
  public void test224()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration((byte)25);
      int int0 = subject_GameConfiguration0.getSize();
      assertEquals(25, int0);
  }

  @Test(timeout = 4000)
  public void test225()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(5);
      subject_GameConfiguration0.getPlayers();
      assertEquals(5, subject_GameConfiguration0.getSize());
  }

  @Test(timeout = 4000)
  public void test226()  throws Throwable  {
      Subject.StringAlgorithms subject_StringAlgorithms0 = new Subject.StringAlgorithms();
  }

  @Test(timeout = 4000)
  public void test227()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(25);
      Subject.GameConfiguration subject_GameConfiguration1 = subject_GameConfiguration0.clone();
      assertEquals(25, subject_GameConfiguration1.getSize());
      assertNotSame(subject_GameConfiguration1, subject_GameConfiguration0);
  }

  @Test(timeout = 4000)
  public void test228()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 0);
      String string0 = subject_GamePlace0.toString();
      assertEquals("(0, 0)", string0);
  }

  @Test(timeout = 4000)
  public void test229()  throws Throwable  {
      Subject.DateTimeAlgorithms subject_DateTimeAlgorithms0 = new Subject.DateTimeAlgorithms();
  }
}
