/*
 * This file was automatically generated by EvoSuite
 * Sun Apr 19 13:04:13 GMT 2026
 */

package comp5111.assignment.cut;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import comp5111.assignment.cut.SubjectSelected;
import java.nio.ByteBuffer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

public class SubjectSelected_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("oFf");
      int[] intArray0 = SubjectSelected.getVersionNo("--FBY,O");
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("no");
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      // Undeclared exception!
      try { 
        SubjectSelected.parseNumber("-l");
      } catch(NumberFormatException e) {
         //
         // -l
         //
         verifyException("comp5111.assignment.cut.SubjectSelected", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("oFF");
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("NO");
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("yej");
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      // Undeclared exception!
      try { 
        SubjectSelected.parseNumber("-jd#xO[;g/<`FCil");
      } catch(NumberFormatException e) {
         //
         // -jd#xO[;g/<`FCil
         //
         verifyException("comp5111.assignment.cut.SubjectSelected", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("tp4(");
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("Fwx^f");
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Number number0 = SubjectSelected.parseNumber("6D");
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("Tz0|");
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("oFq");
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      // Undeclared exception!
      try { 
        SubjectSelected.parseNumber("&7}Ee5C8");
      } catch(NumberFormatException e) {
         //
         // For input string: \"&7}Ee5C8\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("oN");
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("y");
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("YFa");
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      // Undeclared exception!
      try { 
        SubjectSelected.parseNumber(".l");
      } catch(NumberFormatException e) {
         //
         // .l
         //
         verifyException("comp5111.assignment.cut.SubjectSelected", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Number number0 = SubjectSelected.parseNumber("5l");
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("of ");
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      // Undeclared exception!
      try { 
        SubjectSelected.parseNumber("m>Z:G#SiF");
      } catch(NumberFormatException e) {
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("N");
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("F");
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Number number0 = SubjectSelected.parseNumber(".7");
      byte[] byteArray0 = new byte[1];
      byteArray0[0] = (byte) (-44);
      ByteBuffer byteBuffer0 = ByteBuffer.wrap(byteArray0);
      // Undeclared exception!
      try { 
        SubjectSelected.decodeOctets((-189), byteBuffer0, (StringBuilder) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("comp5111.assignment.cut.SubjectSelected", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      // Undeclared exception!
      try { 
        SubjectSelected.parseNumber("u64+h`SGvLS}XEL");
      } catch(NumberFormatException e) {
         //
         // u64+h`SGvLS}XEL
         //
         verifyException("comp5111.assignment.cut.SubjectSelected", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("f46#/");
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("Ov");
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("n");
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("oyv");
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("O}W");
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("oy");
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("nl");
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("T");
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("t");
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("f");
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("NU");
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("Y");
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      // Undeclared exception!
      try { 
        SubjectSelected.parseNumber("nl");
      } catch(NumberFormatException e) {
         //
         // nl
         //
         verifyException("comp5111.assignment.cut.SubjectSelected", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Number number0 = SubjectSelected.parseNumber("0");
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      // Undeclared exception!
      try { 
        SubjectSelected.parseNumber("-e0");
      } catch(NumberFormatException e) {
         //
         // No digits found.
         //
         verifyException("java.math.BigDecimal", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      // Undeclared exception!
      try { 
        SubjectSelected.parseNumber("CMYQxy`F|R?XE2>!.2S");
      } catch(NumberFormatException e) {
         //
         // CMYQxy`F|R?XE2>!.2S
         //
         verifyException("comp5111.assignment.cut.SubjectSelected", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      // Undeclared exception!
      try { 
        SubjectSelected.parseNumber(")isUT(eLm]E'azL");
      } catch(NumberFormatException e) {
         //
         // )isUT(eLm]E'azL
         //
         verifyException("comp5111.assignment.cut.SubjectSelected", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("yg1");
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      // Undeclared exception!
      try { 
        SubjectSelected.parseNumber("comp511.assignment.cut.SubjectSelected");
      } catch(NumberFormatException e) {
         //
         // Character array is missing \"e\" notation exponential mark.
         //
         verifyException("java.math.BigDecimal", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      ByteBuffer byteBuffer0 = ByteBuffer.allocate(1);
      StringBuilder stringBuilder0 = new StringBuilder();
      int int0 = SubjectSelected.decodeOctets(135, byteBuffer0, stringBuilder0);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      int[] intArray0 = SubjectSelected.getVersionNo("d..g+MEMwL;t");
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      boolean boolean0 = SubjectSelected.startsWithIgnoreCase((String) null, (String) null);
      Number number0 = SubjectSelected.parseNumber((String) null);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      // Undeclared exception!
      try { 
        SubjectSelected.parseNumber("S(:'JV6D");
      } catch(NumberFormatException e) {
         //
         // Character S is neither a decimal digit number, decimal point, nor \"e\" notation exponential mark.
         //
         verifyException("java.math.BigDecimal", e);
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("--yg1");
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      // Undeclared exception!
      try { 
        SubjectSelected.parseNumber("L|d_9eG>^E");
      } catch(NumberFormatException e) {
         //
         // L|d_9eG>^E
         //
         verifyException("comp5111.assignment.cut.SubjectSelected", e);
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      int[] intArray0 = SubjectSelected.getVersionNo("uC.c:Xpej26y0xd-I");
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      int[] intArray0 = SubjectSelected.getVersionNo((String) null);
      String string0 = SubjectSelected.padLeft((String) null, (short) (-2497), 'd');
      Boolean boolean0 = SubjectSelected.strToBoolean("Q^P");
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("Q^lP");
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      // Undeclared exception!
      try { 
        SubjectSelected.strToBoolean((String) null, "Qp", "92)~Tj6)CR,`IsC(", "Qp");
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean((String) null, "yg1", (String) null, "yg1");
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean((String) null, (String) null, (String) null, "j");
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      // Undeclared exception!
      try { 
        SubjectSelected.parseNumber("uC.c:Xpej26y0xd-I");
      } catch(NumberFormatException e) {
         //
         // uC.c:Xpej26y0xd-I
         //
         verifyException("comp5111.assignment.cut.SubjectSelected", e);
      }
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      boolean boolean0 = SubjectSelected.startsWithIgnoreCase("0x-0", (String) null);
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      Number number0 = SubjectSelected.parseNumber("-0");
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("Q^P");
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean((String) null);
      String string0 = SubjectSelected.padRight((String) null, (short)78, '_');
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("0x");
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      Number number0 = SubjectSelected.parseNumber("--L|d_9eG>^E");
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      // Undeclared exception!
      try { 
        SubjectSelected.parseNumber("0x");
      } catch(NumberFormatException e) {
         //
         // For input string: \"\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("&");
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      Number number0 = SubjectSelected.parseNumber("p");
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      // Undeclared exception!
      try { 
        SubjectSelected.parseNumber("u$f");
      } catch(NumberFormatException e) {
      }
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      // Undeclared exception!
      try { 
        SubjectSelected.parseNumber("-0x");
      } catch(NumberFormatException e) {
         //
         // For input string: \"-\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      int int0 = SubjectSelected.extractIntInStr((String) null);
      int[] intArray0 = SubjectSelected.getVersionNo((String) null);
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      // Undeclared exception!
      try { 
        SubjectSelected.parseNumber("IVJ}P'QU1T1Kr^\"2");
      } catch(NumberFormatException e) {
         //
         // For input string: \"IVJ}P'QU\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      ByteBuffer byteBuffer0 = ByteBuffer.allocate(48);
      StringBuilder stringBuilder0 = new StringBuilder();
      int int0 = SubjectSelected.decodeOctets(48, byteBuffer0, stringBuilder0);
  }

  @Test(timeout = 4000)
  public void test70()  throws Throwable  {
      String[] stringArray0 = SubjectSelected.trimArrayElements((String[]) null);
      Boolean boolean0 = SubjectSelected.strToBoolean("8?%");
      // Undeclared exception!
      try { 
        SubjectSelected.parseNumber("8?%");
      } catch(NumberFormatException e) {
         //
         // 8?%
         //
         verifyException("comp5111.assignment.cut.SubjectSelected", e);
      }
  }

  @Test(timeout = 4000)
  public void test71()  throws Throwable  {
      char[] charArray0 = new char[5];
      charArray0[0] = 't';
      charArray0[1] = '{';
      charArray0[2] = 'u';
      charArray0[3] = 'y';
      String string0 = SubjectSelected.parseToken("Lan1{Dp", charArray0);
  }

  @Test(timeout = 4000)
  public void test72()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("|", "df'?&", "|", "df'?&");
  }

  @Test(timeout = 4000)
  public void test73()  throws Throwable  {
      String[] stringArray0 = new String[0];
      String[] stringArray1 = SubjectSelected.trimArrayElements(stringArray0);
      Boolean boolean0 = SubjectSelected.strToBoolean("");
  }

  @Test(timeout = 4000)
  public void test74()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("-0");
      boolean boolean1 = SubjectSelected.startsWithIgnoreCase("-0", "--");
  }

  @Test(timeout = 4000)
  public void test75()  throws Throwable  {
      Number number0 = SubjectSelected.parseNumber((String) null);
  }

  @Test(timeout = 4000)
  public void test76()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("", "", "", "");
      String[] stringArray0 = new String[1];
      String[] stringArray1 = SubjectSelected.trimArrayElements(stringArray0);
  }

  @Test(timeout = 4000)
  public void test77()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean((String) null, (String) null, (String) null, (String) null);
  }

  @Test(timeout = 4000)
  public void test78()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      // Undeclared exception!
      try { 
        SubjectSelected.enlarge((short)46, byteArray0, (short)46);
      } catch(ArrayIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test79()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("");
      // Undeclared exception!
      try { 
        SubjectSelected.strToBoolean("", (String) null, (String) null, (String) null);
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("comp5111.assignment.cut.SubjectSelected", e);
      }
  }

  @Test(timeout = 4000)
  public void test80()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("H^(7?N");
      boolean boolean1 = SubjectSelected.startsWithIgnoreCase("0", "H^(7?N");
  }

  @Test(timeout = 4000)
  public void test81()  throws Throwable  {
      String string0 = SubjectSelected.padRight("", (short)1415, '@');
  }

  @Test(timeout = 4000)
  public void test82()  throws Throwable  {
      String string0 = SubjectSelected.padRight("", (short) (-751), '@');
  }

  @Test(timeout = 4000)
  public void test83()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      // Undeclared exception!
      try { 
        SubjectSelected.enlarge((short) (-5), byteArray0, (short) (-5));
      } catch(ArrayIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test84()  throws Throwable  {
      Number number0 = SubjectSelected.parseNumber("");
  }

  @Test(timeout = 4000)
  public void test85()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("-0x", "Q^lP", "Q^lP", "-0x");
  }

  @Test(timeout = 4000)
  public void test86()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("H^(7?N", "H^(7?N", "H^(7?N", "H^(7?N");
  }

  @Test(timeout = 4000)
  public void test87()  throws Throwable  {
      Boolean boolean0 = SubjectSelected.strToBoolean("H^(7?N");
      String[] stringArray0 = new String[3];
      stringArray0[0] = "H^(7?N";
      String[] stringArray1 = SubjectSelected.trimArrayElements(stringArray0);
  }

  @Test(timeout = 4000)
  public void test88()  throws Throwable  {
      String[] stringArray0 = new String[1];
      String[] stringArray1 = SubjectSelected.trimArrayElements(stringArray0);
  }

  @Test(timeout = 4000)
  public void test89()  throws Throwable  {
      boolean boolean0 = SubjectSelected.startsWithIgnoreCase("0x-0", "0x-0");
  }

  @Test(timeout = 4000)
  public void test90()  throws Throwable  {
      String string0 = SubjectSelected.padLeft("<`", (short) (-822), 'T');
      char[] charArray0 = new char[2];
      charArray0[0] = 'T';
      String string1 = SubjectSelected.parseToken("<`", charArray0);
  }

  @Test(timeout = 4000)
  public void test91()  throws Throwable  {
      String string0 = SubjectSelected.padLeft("", (short)1415, 'P');
  }

  @Test(timeout = 4000)
  public void test92()  throws Throwable  {
      int[] intArray0 = SubjectSelected.getVersionNo("8.");
  }

  @Test(timeout = 4000)
  public void test93()  throws Throwable  {
      // Undeclared exception!
      try { 
        SubjectSelected.parseNumber("Z<");
      } catch(NumberFormatException e) {
         //
         // Z<
         //
         verifyException("comp5111.assignment.cut.SubjectSelected", e);
      }
  }

  @Test(timeout = 4000)
  public void test94()  throws Throwable  {
      int int0 = SubjectSelected.extractIntInStr(".Rs0y;`");
  }

  @Test(timeout = 4000)
  public void test95()  throws Throwable  {
      char[] charArray0 = new char[1];
      String string0 = SubjectSelected.parseToken("&^Ua", charArray0);
  }

  @Test(timeout = 4000)
  public void test96()  throws Throwable  {
      int[] intArray0 = SubjectSelected.getVersionNo("");
  }

  @Test(timeout = 4000)
  public void test97()  throws Throwable  {
      int[] intArray0 = SubjectSelected.getVersionNo("UmffPV/zU-5*W'-");
  }

  @Test(timeout = 4000)
  public void test98()  throws Throwable  {
      SubjectSelected subjectSelected0 = new SubjectSelected();
  }
}
