/*
 * This file was automatically generated by EvoSuite
 * Sun Apr 19 05:36:14 GMT 2026
 */

package comp5111.assignment.cut;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import comp5111.assignment.cut.Subject;
import java.nio.ByteBuffer;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.System;
import org.junit.runner.RunWith;

// @RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class Subject_evosuite1_ESTest {

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      Subject subject0 = new Subject();
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("yeA");
      int int0 = 1;
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[9];
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayerArray0[0] = subject_GamePlayer0;
      Subject.GamePlayer subject_GamePlayer1 = subject0.new GamePlayer("yeA");
      subject_GamePlayerArray0[1] = subject_GamePlayer1;
      Subject.GamePlayer subject_GamePlayer2 = subject_GamePlayer0.clone();
      subject_GamePlayerArray0[2] = subject_GamePlayer2;
      Subject.GamePlayer subject_GamePlayer3 = subject0.new GamePlayer();
      subject_GamePlayerArray0[3] = subject_GamePlayer3;
      Subject subject1 = new Subject();
      Subject.GamePlayer subject_GamePlayer4 = subject1.new GamePlayer("yeA");
      subject_GamePlayerArray0[4] = subject_GamePlayer4;
      Subject.GamePlayer subject_GamePlayer5 = subject1.new GamePlayer();
      subject_GamePlayerArray0[5] = subject_GamePlayer5;
      Subject.GamePlayer subject_GamePlayer6 = subject0.new GamePlayer();
      subject_GamePlayerArray0[6] = subject_GamePlayer6;
      int int1 = 4879726;
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(4879726);
      } catch(IllegalArgumentException e) {
         //
         // size of gameboard must be an odd number
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("of?");
      Subject subject0 = new Subject();
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("oFO");
      Subject subject0 = new Subject();
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("NO");
      Subject subject0 = new Subject();
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("-3L");
      Subject subject0 = new Subject();
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      Subject subject0 = new Subject();
      List<String> list0 = Subject.DateTimeAlgorithms.listDatesBetween(117, 117, 117, 117, 117, 117);
      List<String> list1 = Subject.DateTimeAlgorithms.listDatesBetween((-503), 76, 116, 117, 116, 76);
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("On");
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("gE^sf1vRrW<xtse0");
      } catch(NumberFormatException e) {
         //
         // For input string: \"gE^sf1v\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      Subject subject0 = new Subject();
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("yE/");
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("F CjR");
      Subject subject0 = new Subject();
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      subject_GamePlayerArray0[0] = subject_GamePlayer0;
      subject_GamePlayerArray0[1] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(25, subject_GamePlayerArray0);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1, 1);
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      int[] intArray0 = subject_GameConfiguration0.countPiecesPerPlayer();
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("tBy^");
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      subject_GamePlayerArray0[1] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7, subject_GamePlayerArray0);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(3, 7);
      subject_GamePlace0.y(3);
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      } catch(IllegalArgumentException e) {
         //
         // piece cannot be put at central place initially
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("TrK6");
      Subject subject0 = new Subject();
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      subject_GamePlayerArray0[1] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(25, subject_GamePlayerArray0);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(3, 25);
      subject_GamePlace0.y(3);
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      List<Subject.GamePlace> list0 = subject_GameConfiguration0.getPlacesOfPlayer((Subject.GamePlayer) null);
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("FA'cR");
      Subject subject0 = new Subject();
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("fAxeU");
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("-$lY|PH&oY~<9L");
      } catch(NumberFormatException e) {
         //
         // -$lY|PH&oY~<9L
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("no");
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      subject_GamePlayerArray0[1] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(25, subject_GamePlayerArray0);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(3, 25);
      subject_GamePlace0.y(3);
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      int[] intArray0 = subject_GameConfiguration0.countPiecesPerPlayer();
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      subject_GamePlayerArray0[1] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(9, subject_GamePlayerArray0);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(3, 9);
      subject_GamePlace0.y(8);
      Subject.GamePlayer subject_GamePlayer1 = subject0.new GamePlayer();
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      List<Subject.GamePlace> list0 = subject_GameConfiguration0.getEmptyPlaces();
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      subject_GamePlayerArray0[1] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(25, subject_GamePlayerArray0);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(17, 25);
      subject_GamePlace0.y(17);
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      String string0 = subject_GameConfiguration0.toString();
      int[] intArray0 = subject_GameConfiguration0.countPiecesPerPlayer();
      boolean boolean0 = subject_GameConfiguration0.isBoardSymmetric();
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      subject_GamePlayerArray0[1] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(25, subject_GamePlayerArray0);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-14), 25);
      subject_GamePlace0.y((-14));
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      } catch(IllegalArgumentException e) {
         //
         // the place(-14, -14) must be inside the gameboard
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      subject_GamePlayerArray0[1] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(25, subject_GamePlayerArray0);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(3, 25);
      subject_GamePlace0.y(3);
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      boolean boolean0 = subject_GameConfiguration0.isBoardSymmetric();
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      subject_GamePlayerArray0[1] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(25, subject_GamePlayerArray0);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(3, 25);
      subject_GamePlace0.y(8);
      Subject.GamePlayer subject_GamePlayer1 = subject_GamePlayer0.clone();
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      boolean boolean0 = subject_GameConfiguration0.isBoardSymmetric();
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      subject_GamePlayerArray0[1] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(25, subject_GamePlayerArray0);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(17, 25);
      subject_GamePlace0.y((-2767));
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      } catch(IllegalArgumentException e) {
         //
         // the place(17, -2767) must be inside the gameboard
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      subject_GamePlayerArray0[1] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(25, subject_GamePlayerArray0);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(3, 25);
      subject_GamePlace0.y(3);
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      List<Subject.GamePlace> list0 = subject_GameConfiguration0.getPlacesOfPlayer(subject_GamePlayer0);
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      subject_GamePlayerArray0[1] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(9, subject_GamePlayerArray0);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(3, 9);
      subject_GamePlace0.y(8);
      Subject.GamePlayer subject_GamePlayer1 = subject0.new GamePlayer();
      subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("May");
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("oK");
      Subject subject0 = new Subject();
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Dec");
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      subject_GamePlayerArray0[1] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(25, subject_GamePlayerArray0);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(17, 25);
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      } catch(IllegalArgumentException e) {
         //
         // the place(17, 25) must be inside the gameboard
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      Subject subject0 = new Subject();
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Jul");
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      subject_GamePlayerArray0[0] = subject_GamePlayer0;
      subject_GamePlayerArray0[1] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(9, subject_GamePlayerArray0);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(9, 9);
      Subject.GamePlayer subject_GamePlayer1 = subject0.new GamePlayer();
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      } catch(IllegalArgumentException e) {
         //
         // the place(9, 9) must be inside the gameboard
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      Subject subject0 = new Subject();
      byte[] byteArray0 = new byte[7];
      byteArray0[0] = (byte)31;
      byteArray0[1] = (byte)45;
      byteArray0[2] = (byte)66;
      byteArray0[3] = (byte)4;
      byteArray0[4] = (byte) (-67);
      byteArray0[5] = (byte)5;
      byteArray0[6] = (byte)116;
      ByteBuffer byteBuffer0 = ByteBuffer.wrap(byteArray0);
      StringBuilder stringBuilder0 = new StringBuilder();
      Subject subject1 = new Subject();
      int int0 = Subject.StringAlgorithms.decodeOctets(111, byteBuffer0, stringBuilder0);
      Number number0 = Subject.StringAlgorithms.parseNumber("");
      byte[] byteArray1 = new byte[1];
      byteArray1[0] = (byte) (-67);
      ByteBuffer byteBuffer1 = ByteBuffer.wrap(byteArray1);
      int int1 = Subject.StringAlgorithms.decodeOctets(131, byteBuffer1, stringBuilder0);
      // Undeclared exception!
      try { 
        ByteBuffer.wrap(byteArray1, 17, (int) (byte)5);
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.ByteBuffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("pE5SL");
      } catch(NumberFormatException e) {
         //
         // pE5SL
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("f");
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("N6");
      Subject subject0 = new Subject();
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("y");
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("-0");
      System.setCurrentTimeMillis((-3276L));
      List<String> list0 = Subject.DateTimeAlgorithms.listDatesBetween(5202804, 5, 5, 5, 5, 5);
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("ny");
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(111, 111);
      Subject.GamePlace subject_GamePlace1 = subject0.new GamePlace(111, 112);
      boolean boolean0 = subject_GamePlace0.isAdjacent(subject_GamePlace1);
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("n");
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("Op");
      Subject subject0 = new Subject();
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Jan");
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      Subject subject0 = new Subject();
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("F");
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      int int0 = 3;
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      String string0 = subject_GameConfiguration0.toString();
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo("GameConfiguration (size=3)\n. . .\n. . .\n. . .\n");
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("");
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[4];
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayer0.addScore(3);
      Subject.GamePlayer subject_GamePlayer1 = subject_GamePlayer0.clone();
      Subject.GamePlayer subject_GamePlayer2 = subject0.new GamePlayer("GameConfiguration (size=3)\n. . .\n. . .\n. . .\n");
      subject_GamePlayerArray0[1] = subject_GamePlayer2;
      Subject.GamePlayer subject_GamePlayer3 = subject0.new GamePlayer("comp5111.assignment.cut.Subject$DateTimeAlgorithms");
      Subject.GameConfiguration subject_GameConfiguration1 = null;
      try {
        subject_GameConfiguration1 = subject0.new GameConfiguration(3, subject_GamePlayerArray0);
      } catch(IllegalArgumentException e) {
         //
         // there must be exactly two players
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Mar");
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("t");
      Subject subject0 = new Subject();
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(17);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1, (-1));
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      Subject subject0 = new Subject();
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("yYU");
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("Ym8");
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(86400000L);
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("K(-ly`rS2");
      Subject subject0 = new Subject();
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Aug");
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject subject1 = new Subject();
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Apr");
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      Subject subject0 = new Subject();
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(9);
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.lastDayOfMonth(2, 2);
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Feb");
      Subject subject0 = new Subject();
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(86400L);
      Subject subject0 = new Subject();
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      Subject subject0 = new Subject();
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(8);
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Oct");
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject subject1 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject1.new GamePlace((-2115), (-2115));
      Subject.GamePlace subject_GamePlace1 = subject0.new GamePlace((-2115), 23);
      Subject.GamePlace subject_GamePlace2 = subject_GamePlace1.clone();
      boolean boolean0 = subject_GamePlace1.equals(subject_GamePlace0);
      Object object0 = new Object();
      boolean boolean1 = subject_GamePlace0.equals(object0);
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[0];
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(4, subject_GamePlayerArray0);
      } catch(IllegalArgumentException e) {
         //
         // size of gameboard must be an odd number
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("TE`%");
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("Y");
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(11);
      List<Subject.GamePlace> list0 = subject_GameConfiguration0.getEmptyPlaces();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, (-1));
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
      } catch(IllegalArgumentException e) {
         //
         // Place is out of bounds
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("-$lY|PM&q|o5Y.K9L");
      } catch(NumberFormatException e) {
         //
         // -$lY|PM&q|o5Y.K9L
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(5);
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(17);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 17);
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      boolean boolean1 = subject_GameConfiguration0.isBoardFull();
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(5);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(3, 3);
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      Subject subject0 = new Subject();
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(4);
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      ByteBuffer byteBuffer0 = ByteBuffer.wrap(byteArray0);
      StringBuilder stringBuilder0 = new StringBuilder();
      Subject subject0 = new Subject();
      int int0 = Subject.StringAlgorithms.decodeOctets((byte)0, byteBuffer0, stringBuilder0);
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      Subject subject0 = new Subject();
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("T");
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      ByteBuffer byteBuffer0 = ByteBuffer.allocate(2730);
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.decodeOctets(2730, byteBuffer0, (StringBuilder) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject subject1 = new Subject();
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(7);
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      Subject subject0 = new Subject();
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(5752L);
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("N");
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Nov");
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(23, 23);
      boolean boolean0 = subject_GamePlace0.equals(subject_GamePlace0);
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      Subject subject0 = new Subject();
      String string0 = Subject.DateTimeAlgorithms.lastDayOfMonth(11, 11);
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      Subject subject0 = new Subject();
      int int0 = Subject.DateTimeAlgorithms.getQuarter(8);
      Subject subject1 = new Subject();
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      Subject subject0 = new Subject();
      int int0 = Subject.DateTimeAlgorithms.getQuarter(12);
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("uD");
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(12);
      Subject subject0 = new Subject();
      Subject subject1 = new Subject();
      String string1 = Subject.DateTimeAlgorithms.month2MonAbbr(12);
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(5);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-23), (-23));
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("5.6");
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      boolean boolean0 = Subject.StringAlgorithms.startsWithIgnoreCase("", (String) null);
      Subject subject0 = new Subject();
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("fD");
      } catch(NumberFormatException e) {
         //
         // Character f is neither a decimal digit number, decimal point, nor \"e\" notation exponential mark.
         //
         verifyException("java.math.BigDecimal", e);
      }
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("Oct");
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("oK9");
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("lkd>VcU[XL~]&'U%E");
      } catch(NumberFormatException e) {
         //
         // lkd>VcU[XL~]&'U%E
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.calcDaysInMonth(4, 4);
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      int[] intArray0 = subject_GameConfiguration0.countPiecesPerPlayer();
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      List<Subject.GamePlace> list0 = subject_GameConfiguration0.getPlacesOfPlayer(subject_GamePlayer0);
      Subject.GamePlayer subject_GamePlayer1 = subject0.new GamePlayer();
      String string0 = Subject.DateTimeAlgorithms.dayStr(3);
      Subject subject1 = new Subject();
      Subject.GamePlayer[] subject_GamePlayerArray0 = subject_GameConfiguration0.getPlayers();
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(5);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1, 5);
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt(subject_GamePlace1);
      } catch(IllegalArgumentException e) {
         //
         // Place is out of bounds
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(23);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 0);
      Subject.GamePlayer subject_GamePlayer0 = subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(23);
      int int0 = Subject.DateTimeAlgorithms.daysInYear(23);
      Subject.GamePlayer[][] subject_GamePlayerArray0 = subject_GameConfiguration0.getInitialBoard();
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      boolean boolean0 = subject_GameConfiguration0.isBoardSymmetric();
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(3, 3);
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month((String) null);
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      Subject subject0 = new Subject();
      String string0 = Subject.DateTimeAlgorithms.formatFullDate(11, 11, 11);
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("M}F");
      } catch(NumberFormatException e) {
      }
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("j{\"fb$fI%nrkbn-;/CL");
      } catch(NumberFormatException e) {
         //
         // j{\"fb$fI%nrkbn-;/CL
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("9L");
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("Jul");
      } catch(NumberFormatException e) {
         //
         // Jul
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.calcDaysInMonth((-386), (-161));
      int int1 = Subject.DateTimeAlgorithms.daysInYear(1000);
      int int2 = Subject.DateTimeAlgorithms.monAbbr2month("");
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      Subject subject0 = new Subject();
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean((String) null, "/#{pRxGu739gHb6#\"", (String) null, "/#{pRxGu739gHb6#\"");
      Boolean boolean1 = Subject.StringAlgorithms.strToBoolean("/#{pRxGu739gHb6#\"");
      int int0 = Subject.DateTimeAlgorithms.daysInYear(133);
      Subject subject1 = new Subject();
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("*I<k");
      } catch(NumberFormatException e) {
         //
         // *I<k
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo("T9'.=Slgt*kld7U..(?");
  }

  @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo("4");
  }

  @Test(timeout = 4000)
  public void test105()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(6);
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("Jun", "Jun", "Jun", "Jun");
  }

  @Test(timeout = 4000)
  public void test106()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("5D");
  }

  @Test(timeout = 4000)
  public void test107()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(23, 23);
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
      subject_GamePlace1.x((-1837));
      boolean boolean0 = subject_GamePlace0.equals(subject_GamePlace1);
  }

  @Test(timeout = 4000)
  public void test108()  throws Throwable  {
      Subject subject0 = new Subject();
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(604800L);
  }

  @Test(timeout = 4000)
  public void test109()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("-0xTVC%");
      } catch(NumberFormatException e) {
         //
         // For input string: \"-TVC%\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test110()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("----");
  }

  @Test(timeout = 4000)
  public void test111()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber(";e4");
      } catch(NumberFormatException e) {
         //
         // Character ; is neither a decimal digit number, decimal point, nor \"e\" notation exponential mark.
         //
         verifyException("java.math.BigDecimal", e);
      }
  }

  @Test(timeout = 4000)
  public void test112()  throws Throwable  {
      Subject subject0 = new Subject();
      List<String> list0 = Subject.DateTimeAlgorithms.listDatesBetween(1245, 2062, (-3569), (-1739), (-685), 1245);
      Subject subject1 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject1.new GamePlace((-1209), (-3569));
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
      Subject.GamePlace subject_GamePlace2 = subject_GamePlace0.clone();
      Subject.GamePlace subject_GamePlace3 = subject_GamePlace0.clone();
      subject_GamePlace1.y(0);
      String[] stringArray0 = Subject.StringAlgorithms.trimArrayElements((String[]) null);
  }

  @Test(timeout = 4000)
  public void test113()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      Subject.GamePlayer subject_GamePlayer1 = subject_GamePlayer0.clone();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-540), (-304));
      Subject subject1 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(5);
      Subject.GamePlace subject_GamePlace1 = subject0.new GamePlace((-135335516), 169);
      String string0 = Subject.DateTimeAlgorithms.dayStr(5);
      int int0 = subject_GameConfiguration0.getSize();
  }

  @Test(timeout = 4000)
  public void test114()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(121, (-1237));
      boolean boolean0 = subject_GamePlace0.isAdjacent((Subject.GamePlace) null);
  }

  @Test(timeout = 4000)
  public void test115()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("comp5111.assignment.cut.Subject$StringAlgorithms");
      } catch(NumberFormatException e) {
         //
         // comp5111.assignment.cut.Subject$StringAlgorithms
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test116()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("\".;");
      } catch(NumberFormatException e) {
         //
         // \".;
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test117()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("GJ0E881kg.M^E");
      } catch(NumberFormatException e) {
         //
         // GJ0E881kg.M^E
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test118()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("Sep");
      } catch(NumberFormatException e) {
         //
         // Sep
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test119()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter((short)1);
  }

  @Test(timeout = 4000)
  public void test120()  throws Throwable  {
      Subject subject0 = new Subject();
      int int0 = Subject.DateTimeAlgorithms.getQuarter(5);
  }

  @Test(timeout = 4000)
  public void test121()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(32);
  }

  @Test(timeout = 4000)
  public void test122()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter((-4));
  }

  @Test(timeout = 4000)
  public void test123()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("J F)+5+X:?\"ABl\"@d");
      } catch(NumberFormatException e) {
         //
         // Character J is neither a decimal digit number, decimal point, nor \"e\" notation exponential mark.
         //
         verifyException("java.math.BigDecimal", e);
      }
  }

  @Test(timeout = 4000)
  public void test124()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("8");
  }

  @Test(timeout = 4000)
  public void test125()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[1];
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayerArray0[0] = subject_GamePlayer0;
      boolean boolean0 = subject_GamePlayer0.equals(subject_GamePlayer0);
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDateStrings((String) null, (String) null);
  }

  @Test(timeout = 4000)
  public void test126()  throws Throwable  {
      Subject subject0 = new Subject();
      Number number0 = Subject.StringAlgorithms.parseNumber(";");
  }

  @Test(timeout = 4000)
  public void test127()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(23);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-1), (-1));
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
      } catch(IllegalArgumentException e) {
         //
         // Place is out of bounds
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test128()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("");
  }

  @Test(timeout = 4000)
  public void test129()  throws Throwable  {
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo((String) null);
  }

  @Test(timeout = 4000)
  public void test130()  throws Throwable  {
      Subject subject0 = new Subject();
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo("AJCxoj|.");
  }

  @Test(timeout = 4000)
  public void test131()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      List<Subject.GamePlace> list0 = subject_GameConfiguration0.getPlacesOfPlayer(subject_GamePlayer0);
  }

  @Test(timeout = 4000)
  public void test132()  throws Throwable  {
      StringBuilder stringBuilder0 = new StringBuilder(3);
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDates(3, 3, 3, 3, 3, 3);
  }

  @Test(timeout = 4000)
  public void test133()  throws Throwable  {
      StringBuilder stringBuilder0 = new StringBuilder();
      // Undeclared exception!
      try { 
        Subject.DateTimeAlgorithms.daysBetweenDates(1, 1, 13, 1, 13, 13);
      } catch(IllegalArgumentException e) {
         //
         // Invalid date
         //
         verifyException("comp5111.assignment.cut.Subject$DateTimeAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test134()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("&s)m:");
  }

  @Test(timeout = 4000)
  public void test135()  throws Throwable  {
      Subject subject0 = new Subject();
      int int0 = Subject.DateTimeAlgorithms.monthsBetween(1268, 6, 1268, 1097);
  }

  @Test(timeout = 4000)
  public void test136()  throws Throwable  {
      // Undeclared exception!
      Subject.DateTimeAlgorithms.listDatesBetween(9, 9, 9, 9, 9, 9);
  }

  @Test(timeout = 4000)
  public void test137()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber((String) null);
  }

  @Test(timeout = 4000)
  public void test138()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("l");
  }

  @Test(timeout = 4000)
  public void test139()  throws Throwable  {
      Subject subject0 = new Subject();
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("l");
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-1036), (-1036));
      boolean boolean1 = subject_GamePlace0.equals((Object) null);
  }

  @Test(timeout = 4000)
  public void test140()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("0xl;");
  }

  @Test(timeout = 4000)
  public void test141()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(11);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(11, 11);
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
      } catch(IllegalArgumentException e) {
         //
         // Place is out of bounds
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test142()  throws Throwable  {
      System.setCurrentTimeMillis(2368L);
      int int0 = 0;
      byte[] byteArray0 = new byte[0];
      Subject.StringAlgorithms.enlarge(0, byteArray0, 0);
      Subject subject0 = new Subject();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayerArray0[0] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(4);
      } catch(IllegalArgumentException e) {
         //
         // size of gameboard must be an odd number
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test143()  throws Throwable  {
      byte[] byteArray0 = new byte[2];
      byteArray0[0] = (byte)41;
      byteArray0[1] = (byte)41;
      Subject.StringAlgorithms.enlarge(3, byteArray0, 0);
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(25, (-3583));
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
      subject_GamePlace1.x(2120);
      boolean boolean0 = subject_GamePlace1.equals(subject0);
      Boolean boolean1 = Subject.StringAlgorithms.strToBoolean("");
  }

  @Test(timeout = 4000)
  public void test144()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("0xl;");
      } catch(NumberFormatException e) {
         //
         // For input string: \"l;\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test145()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(5);
      int int0 = Subject.DateTimeAlgorithms.getQuarter(5);
      subject_GameConfiguration0.clearInitialBoard();
      String string0 = Subject.DateTimeAlgorithms.dayStr(5);
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("-QTP?");
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("-QTP?");
      } catch(NumberFormatException e) {
         //
         // -QTP?
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test146()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      String string0 = subject_GameConfiguration0.toString();
  }

  @Test(timeout = 4000)
  public void test147()  throws Throwable  {
      Subject subject0 = new Subject();
      String string0 = Subject.DateTimeAlgorithms.formatFullDate(3, 3, 3);
  }

  @Test(timeout = 4000)
  public void test148()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean(",S");
  }

  @Test(timeout = 4000)
  public void test149()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("o|");
  }

  @Test(timeout = 4000)
  public void test150()  throws Throwable  {
      boolean boolean0 = Subject.StringAlgorithms.startsWithIgnoreCase("!m5fco'\"Nbu<7b8K", "!m5fco'\"Nbu<7b8K");
      String string0 = null;
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.strToBoolean((String) null, "!m5fco'\"Nbu<7b8K", "!m5fco'\"Nbu<7b8K", "!m5fco'\"Nbu<7b8K");
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test151()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean((String) null, (String) null, (String) null, "=Y,Zf-S?tO[U");
      Subject subject0 = new Subject();
  }

  @Test(timeout = 4000)
  public void test152()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean((String) null, (String) null, (String) null, (String) null);
  }

  @Test(timeout = 4000)
  public void test153()  throws Throwable  {
      boolean boolean0 = Subject.StringAlgorithms.startsWithIgnoreCase("B@S", "!m5Bc'qNbu<7b8K");
  }

  @Test(timeout = 4000)
  public void test154()  throws Throwable  {
      Subject subject0 = new Subject();
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(1);
  }

  @Test(timeout = 4000)
  public void test155()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("Jul");
  }

  @Test(timeout = 4000)
  public void test156()  throws Throwable  {
      Subject subject0 = new Subject();
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDateStrings("l;", (String) null);
      boolean boolean0 = Subject.StringAlgorithms.startsWithIgnoreCase("e{!HSPlToRITk33e7`L", "3rd");
  }

  @Test(timeout = 4000)
  public void test157()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[1];
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(25, subject_GamePlayerArray0);
      } catch(IllegalArgumentException e) {
         //
         // there must be exactly two players
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test158()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr(1);
  }

  @Test(timeout = 4000)
  public void test159()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("qC");
  }

  @Test(timeout = 4000)
  public void test160()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Jun");
  }

  @Test(timeout = 4000)
  public void test161()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("/E0^");
  }

  @Test(timeout = 4000)
  public void test162()  throws Throwable  {
      String string0 = Subject.StringAlgorithms.padLeft((String) null, (short) (-19), 'P');
  }

  @Test(timeout = 4000)
  public void test163()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.DateTimeAlgorithms subject_DateTimeAlgorithms0 = new Subject.DateTimeAlgorithms();
      Number number0 = Subject.StringAlgorithms.parseNumber("");
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDateStrings("--~^", "K^ziXx");
  }

  @Test(timeout = 4000)
  public void test164()  throws Throwable  {
      Subject subject0 = new Subject();
      int int0 = Subject.DateTimeAlgorithms.monthsBetween((-680), 10, 3760, (-680));
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(3760);
      } catch(IllegalArgumentException e) {
         //
         // size of gameboard must be an odd number
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test165()  throws Throwable  {
      Subject subject0 = new Subject();
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDateStrings("-0x<GP-Ke8RG~m]X", "-0x<GP-Ke8RG~m]X");
  }

  @Test(timeout = 4000)
  public void test166()  throws Throwable  {
      boolean boolean0 = Subject.StringAlgorithms.startsWithIgnoreCase("!m5fco'\"Nbu<7b8K", "!m5fco'\"Nbu<7b8K");
      Subject.DateTimeAlgorithms subject_DateTimeAlgorithms0 = new Subject.DateTimeAlgorithms();
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDateStrings("!m5fco'\"Nbu<7b8K", "!m5fco'\"Nbu<7b8K");
      char[] charArray0 = new char[6];
      charArray0[0] = 'U';
      charArray0[1] = 'U';
      charArray0[2] = '9';
      charArray0[3] = '3';
      charArray0[4] = '9';
      charArray0[5] = 'o';
      String string0 = Subject.StringAlgorithms.parseToken("!m5fco'\"Nbu<7b8K", charArray0);
  }

  @Test(timeout = 4000)
  public void test167()  throws Throwable  {
      Subject.StringAlgorithms subject_StringAlgorithms0 = new Subject.StringAlgorithms();
  }

  @Test(timeout = 4000)
  public void test168()  throws Throwable  {
      String string0 = Subject.StringAlgorithms.padRight((String) null, (short) (-19), 'P');
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("", (String) null, (String) null, "");
  }

  @Test(timeout = 4000)
  public void test169()  throws Throwable  {
      List<String> list0 = Subject.DateTimeAlgorithms.listDatesBetween(7, 7, 7, 7, 7, 37);
  }

  @Test(timeout = 4000)
  public void test170()  throws Throwable  {
      // Undeclared exception!
      Subject.DateTimeAlgorithms.listDatesBetween(6, 6, 6, 6, 6, 6);
  }

  @Test(timeout = 4000)
  public void test171()  throws Throwable  {
      // Undeclared exception!
      Subject.DateTimeAlgorithms.listDatesBetween(7, 7, 7, 7, 7, 7);
  }

  @Test(timeout = 4000)
  public void test172()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(2);
  }

  @Test(timeout = 4000)
  public void test173()  throws Throwable  {
      boolean boolean0 = Subject.StringAlgorithms.startsWithIgnoreCase((String) null, (String) null);
      Number number0 = Subject.StringAlgorithms.parseNumber((String) null);
  }

  @Test(timeout = 4000)
  public void test174()  throws Throwable  {
      Subject subject0 = new Subject();
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr((-1811));
  }

  @Test(timeout = 4000)
  public void test175()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monthsBetween(28, 28, 28, 28);
  }

  @Test(timeout = 4000)
  public void test176()  throws Throwable  {
      Subject subject0 = new Subject();
      int int0 = Subject.DateTimeAlgorithms.monthsBetween(8, 8, 8, 8);
  }

  @Test(timeout = 4000)
  public void test177()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      Subject.GamePlayer subject_GamePlayer1 = subject_GamePlayer0.clone();
      String string0 = subject_GamePlayer0.getName();
  }

  @Test(timeout = 4000)
  public void test178()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(20, 20);
      boolean boolean0 = subject_GamePlace0.isAdjacent(subject_GamePlace0);
  }

  @Test(timeout = 4000)
  public void test179()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(1081L);
  }

  @Test(timeout = 4000)
  public void test180()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.firstDayOfMonth(10, 10);
  }

  @Test(timeout = 4000)
  public void test181()  throws Throwable  {
      List<String> list0 = Subject.DateTimeAlgorithms.listDatesBetween(0, 2, 2, 0, 1261, 2);
      Subject subject0 = new Subject();
  }

  @Test(timeout = 4000)
  public void test182()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.firstDayOfMonth(34, 34);
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("(invalid)", "(invalid)", "(invalid)", "(invalid)");
  }

  @Test(timeout = 4000)
  public void test183()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString((-4789L));
  }

  @Test(timeout = 4000)
  public void test184()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer((String) null);
      subject_GamePlayer0.addScore(1101);
      int int0 = subject_GamePlayer0.getScore();
  }

  @Test(timeout = 4000)
  public void test185()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.DateTimeAlgorithms.daysBetweenDates(59, 59, 59, 59, 59, 59);
      } catch(IllegalArgumentException e) {
         //
         // Invalid date
         //
         verifyException("comp5111.assignment.cut.Subject$DateTimeAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test186()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.calcDaysInMonth((-1386), (-1386));
  }

  @Test(timeout = 4000)
  public void test187()  throws Throwable  {
      Subject subject0 = new Subject();
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.strToBoolean("''VW,j~9k`zL_m[]", "r", "r", "0xAnonymous Player");
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test188()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Sep");
      Subject subject0 = new Subject();
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("Player B", "Sep", "Player B", "Sep");
  }

  @Test(timeout = 4000)
  public void test189()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr((-16));
  }

  @Test(timeout = 4000)
  public void test190()  throws Throwable  {
      String string0 = Subject.StringAlgorithms.padLeft("a 'T)&A})", (short) (-1), 'n');
  }

  @Test(timeout = 4000)
  public void test191()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(100);
      } catch(IllegalArgumentException e) {
         //
         // size of gameboard must be an odd number
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test192()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("Y@f");
      } catch(NumberFormatException e) {
      }
  }

  @Test(timeout = 4000)
  public void test193()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("May");
      } catch(NumberFormatException e) {
         //
         // May
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test194()  throws Throwable  {
      boolean boolean0 = Subject.StringAlgorithms.startsWithIgnoreCase("!m5fco'\"Nbu<7b8K", "!m5fco'\"Nbu<7b8K");
      Subject subject0 = new Subject();
  }

  @Test(timeout = 4000)
  public void test195()  throws Throwable  {
      Subject.DateTimeAlgorithms subject_DateTimeAlgorithms0 = new Subject.DateTimeAlgorithms();
  }

  @Test(timeout = 4000)
  public void test196()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      Subject.GamePlayer subject_GamePlayer1 = subject0.new GamePlayer();
      boolean boolean0 = subject_GamePlayer0.equals(subject0);
      Object object0 = new Object();
  }

  @Test(timeout = 4000)
  public void test197()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.firstDayOfMonth(175, (-72365114));
  }

  @Test(timeout = 4000)
  public void test198()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(11);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(11, 11);
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      } catch(IllegalArgumentException e) {
         //
         // the player of the piece is unknown
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test199()  throws Throwable  {
      int int0 = 24;
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(24, 24);
      byte[] byteArray0 = new byte[0];
      ByteBuffer byteBuffer0 = ByteBuffer.wrap(byteArray0);
      String string0 = "-0x";
      char[] charArray0 = new char[1];
      char char0 = 'k';
      String string1 = Subject.StringAlgorithms.parseToken("-0x", charArray0);
      StringBuilder stringBuilder0 = new StringBuilder((CharSequence) "-0x");
      // Undeclared exception!
      try { 
        stringBuilder0.insert(24, 'k');
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test200()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayer0.setScore(2656);
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      subject_GamePlayerArray0[1] = subject_GamePlayer0;
  }

  @Test(timeout = 4000)
  public void test201()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDateStrings("qC", "qC");
  }

  @Test(timeout = 4000)
  public void test202()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[2];
      subject_GamePlayerArray0[1] = subject_GamePlayer0;
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(17, subject_GamePlayerArray0);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(17, 17);
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
      } catch(IllegalArgumentException e) {
         //
         // the place(17, 17) must be inside the gameboard
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test203()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayer0.addScore(175);
  }

  @Test(timeout = 4000)
  public void test204()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.calcDaysInMonth(19, 19);
  }

  @Test(timeout = 4000)
  public void test205()  throws Throwable  {
      Subject subject0 = new Subject();
      List<String> list0 = Subject.DateTimeAlgorithms.listDatesBetween(7, 7, 7, 7, 7, (-1));
  }

  @Test(timeout = 4000)
  public void test206()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      boolean boolean0 = subject_GameConfiguration0.isBoardFull();
  }

  @Test(timeout = 4000)
  public void test207()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.lastDayOfMonth(20, 20);
  }

  @Test(timeout = 4000)
  public void test208()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.lastDayOfMonth(1, 1);
  }

  @Test(timeout = 4000)
  public void test209()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monthsBetween((-1386), (-1386), (-1386), (-1386));
  }

  @Test(timeout = 4000)
  public void test210()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(37);
      } catch(IllegalArgumentException e) {
         //
         // size of gameboard is at most 25
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test211()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("ghV@lWAujo");
      Subject subject0 = new Subject();
      Subject subject1 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject1.new GamePlace((-527), (-527));
      int int0 = subject_GamePlace0.manhattanDistance((Subject.GamePlace) null);
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration((-1));
      } catch(IllegalArgumentException e) {
         //
         // size of gameboard must be at least 3
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test212()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayer0.resetScore();
  }

  @Test(timeout = 4000)
  public void test213()  throws Throwable  {
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo("");
  }

  @Test(timeout = 4000)
  public void test214()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("i]G^MUS/_\"");
      Subject.GamePlayer subject_GamePlayer1 = subject_GamePlayer0.clone();
      String string0 = subject_GamePlayer1.toString();
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDateStrings("GamePlayer{name='i]G^MUS/_\"', score=0}", "on=_^V");
  }

  @Test(timeout = 4000)
  public void test215()  throws Throwable  {
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo("2f(V-xbtver.'O<");
  }

  @Test(timeout = 4000)
  public void test216()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr(32);
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("(invalid)");
  }

  @Test(timeout = 4000)
  public void test217()  throws Throwable  {
      List<String> list0 = Subject.DateTimeAlgorithms.listDatesBetween(2606, 2606, 2606, 2606, 2606, 2606);
  }

  @Test(timeout = 4000)
  public void test218()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr(17);
  }

  @Test(timeout = 4000)
  public void test219()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.formatFullDate((-16), (-16), (-16));
  }

  @Test(timeout = 4000)
  public void test220()  throws Throwable  {
      String string0 = Subject.StringAlgorithms.padRight("An", (short)6, 'n');
  }

  @Test(timeout = 4000)
  public void test221()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.formatFullDate(10, 10, 10);
  }

  @Test(timeout = 4000)
  public void test222()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean((String) null);
  }

  @Test(timeout = 4000)
  public void test223()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("GameConfiguration (size=");
  }

  @Test(timeout = 4000)
  public void test224()  throws Throwable  {
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo("NqA>QgKeFUt2Jk$");
  }

  @Test(timeout = 4000)
  public void test225()  throws Throwable  {
      int int0 = Subject.StringAlgorithms.extractIntInStr((String) null);
  }

  @Test(timeout = 4000)
  public void test226()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(23, 23);
      Object object0 = new Object();
      boolean boolean0 = subject_GamePlace0.equals(object0);
  }

  @Test(timeout = 4000)
  public void test227()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-527), (-527));
      subject_GamePlace0.x((-527));
      int int0 = subject_GamePlace0.manhattanDistance(subject_GamePlace0);
  }

  @Test(timeout = 4000)
  public void test228()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(23, 23);
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
      boolean boolean0 = subject_GamePlace0.equals(subject_GamePlace1);
  }

  @Test(timeout = 4000)
  public void test229()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-2003), (-2003));
      subject_GamePlace0.y((-2003));
  }

  @Test(timeout = 4000)
  public void test230()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      List<Subject.GamePlace> list0 = subject_GameConfiguration0.getEmptyPlaces();
  }

  @Test(timeout = 4000)
  public void test231()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(23);
      Subject.GameConfiguration subject_GameConfiguration1 = subject_GameConfiguration0.clone();
  }

  @Test(timeout = 4000)
  public void test232()  throws Throwable  {
      Subject subject0 = new Subject();
      int int0 = Subject.DateTimeAlgorithms.daysInYear((-1344));
      Subject subject1 = new Subject();
      String string0 = Subject.DateTimeAlgorithms.dayStr(1);
      String[] stringArray0 = new String[3];
      stringArray0[0] = "1st";
      stringArray0[1] = "1st";
      stringArray0[2] = "1st";
      String[] stringArray1 = Subject.StringAlgorithms.trimArrayElements(stringArray0);
  }

  @Test(timeout = 4000)
  public void test233()  throws Throwable  {
      String[] stringArray0 = new String[16];
      String[] stringArray1 = Subject.StringAlgorithms.trimArrayElements(stringArray0);
      String string0 = Subject.DateTimeAlgorithms.dayStr((-2093));
      int int0 = Subject.DateTimeAlgorithms.daysInYear((-2093));
  }

  @Test(timeout = 4000)
  public void test234()  throws Throwable  {
      String[] stringArray0 = new String[0];
      String[] stringArray1 = Subject.StringAlgorithms.trimArrayElements(stringArray0);
      int int0 = Subject.DateTimeAlgorithms.daysInYear((-2093));
  }

  @Test(timeout = 4000)
  public void test235()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysInYear(1111);
  }

  @Test(timeout = 4000)
  public void test236()  throws Throwable  {
      String string0 = Subject.StringAlgorithms.padLeft("", (short)1, 'n');
  }

  @Test(timeout = 4000)
  public void test237()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(1);
      } catch(IllegalArgumentException e) {
         //
         // size of gameboard must be at least 3
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test238()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysInYear(1140);
  }

  @Test(timeout = 4000)
  public void test239()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("&s#)m:", "&s#)m:", "&s#)m:", "&s#)m:");
  }
}
