/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 18 13:57:45 GMT 2026
 */

package comp5111.assignment.cut;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import comp5111.assignment.cut.Subject;
import java.nio.ByteBuffer;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

//@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Subject_ESTest_Generate_Evosuite1{

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(9);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 384);
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertEquals(9, subject_GameConfiguration0.getSize());
      assertEquals(384, subject_GamePlace0.y());
      assertTrue(boolean0);
      assertEquals(0, subject_GamePlace0.x());
      assertEquals("(0, 384)", subject_GamePlace0.toString());
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(100, 100);
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(11);
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertEquals(11, subject_GameConfiguration0.getSize());
      assertTrue(boolean0);
      assertEquals("(100, 100)", subject_GamePlace0.toString());
      assertEquals(100, subject_GamePlace0.x());
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(17);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(9, 121);
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Place is out of bounds
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(5);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 0);
      subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
      assertEquals(5, subject_GameConfiguration0.getSize());
      assertEquals(0, subject_GamePlace0.y());
      assertEquals(0, subject_GamePlace0.x());
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(2549, 1190);
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Place is out of bounds
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[0];
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(11, subject_GamePlayerArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // there must be exactly two players
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-1), (-1));
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
      assertEquals("(-1, -1)", subject_GamePlace1.toString());
      
      subject_GamePlace1.y(1);
      int int0 = subject_GamePlace1.manhattanDistance(subject_GamePlace0);
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 0);
      int int0 = subject_GamePlace0.manhattanDistance(subject_GamePlace0);
      assertEquals("(0, 0)", subject_GamePlace0.toString());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(653, (-228949994));
      Subject.GamePlace subject_GamePlace1 = subject0.new GamePlace((-1), (-1));
      boolean boolean0 = subject_GamePlace0.isAdjacent(subject_GamePlace1);
      assertFalse(boolean0);
      assertEquals("(653, -228949994)", subject_GamePlace0.toString());
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(78, (-406));
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
      subject_GamePlace0.y(13);
      boolean boolean0 = subject_GamePlace0.equals(subject_GamePlace1);
      assertEquals("(78, 13)", subject_GamePlace0.toString());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1, 31);
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
      subject_GamePlace1.x(1178);
      boolean boolean0 = subject_GamePlace1.equals(subject_GamePlace0);
      assertEquals("(1178, 31)", subject_GamePlace1.toString());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayer0.addScore(1);
      assertEquals(1, subject_GamePlayer0.getScore());
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monthsBetween((-1115), 12, 12, 12);
      assertEquals(13524, int0);
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monthsBetween(11, 12, 1059, 11);
      assertEquals(12575, int0);
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.firstDayOfMonth(9, 9);
      assertEquals("0009-09-01", string0);
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDateStrings("--iQ\":]#q\"", "Player A");
      assertEquals(Integer.MIN_VALUE, int0);
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDateStrings("0x-0x-+f-]rKs$Oa2", "et5iNCqDXCv_8R)'/K");
      assertEquals(Integer.MIN_VALUE, int0);
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month(";");
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(9);
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(5);
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(3);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr(31);
      assertEquals("31st", string0);
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr((byte)0);
      assertEquals("(invalid)", string0);
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr(13);
      assertEquals("13th", string0);
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(60L);
      assertEquals("1 M", string0);
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(4952L);
      assertEquals("1 H", string0);
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(86448L);
      assertEquals("1 D", string0);
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(604813L);
      assertEquals("1 W", string0);
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      boolean boolean0 = Subject.DateTimeAlgorithms.judgeLeapYear(100);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.DateTimeAlgorithms.daysBetweenDates((-740), 2, (-740), 1115, 1, 3134);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid date
         //
         verifyException("comp5111.assignment.cut.Subject$DateTimeAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysInYear((-815));
      assertEquals(365, int0);
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      List<String> list0 = Subject.DateTimeAlgorithms.listDatesBetween((-406), 10, 10, (-406), 10, (-406));
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      List<String> list0 = Subject.DateTimeAlgorithms.listDatesBetween((-1276), 12, 5071218, (-1), 97, 1483);
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDates(2, 2, 2, 2, 2, 2);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      String string0 = Subject.StringAlgorithms.padRight("", (short)0, 'f');
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      String string0 = Subject.StringAlgorithms.padRight("NX~|^~5]H<", (short)1916, '(');
      String string1 = Subject.StringAlgorithms.padLeft(string0, (short)1916, '6');
      assertNotNull(string1);
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      int int0 = Subject.StringAlgorithms.extractIntInStr("97!");
      assertEquals(97, int0);
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      int int0 = Subject.StringAlgorithms.extractIntInStr("9Lp");
      assertEquals(9, int0);
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo("0xGameConfiguration (size=19)\n. . . . . . . . . . . . . . . . . . .\n. . . . . . . . . . . . . . . . . . .\n. . . . . . . . . . . . . . . . . . .\n. . . . . . . . . . . . . . . . . . .\n. . . . . . . . . . . . . . . . . . .\n. . . . . . . . . . . . . . . . . . .\n. . . . . . . . . . . . . . . . . . .\n. . . . . . . . . . . . . . . . . . .\n. . . . . . . . . . . . . . . . . . .\n. . . . . . . . . . . . . . . . . . .\n. . . . . . . . . . . . . . . . . . .\n. . . . . . . . . . . . . . . . . . .\n. . . . . . . . . . . . . . . . . . .\n. . . . . . . . . . . . . . . . . . .\n. . . . . . . . . . . . . . . . . . .\n. . . . . . . . . . . . . . . . . . .\n. . . . . . . . . . . . . . . . . . .\n. . . . . . . . . . . . . . . . . . .\n. . . . . . . . . . . . . . . . . . .\n");
      assertNull(intArray0);
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("2");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("Nu");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean(">;");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("+");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("{");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(78, 78);
      int int0 = subject_GamePlace0.y();
      assertEquals(78, int0);
      assertEquals(78, subject_GamePlace0.x());
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1002, 966);
      int int0 = subject_GamePlace0.x();
      assertEquals("(1002, 966)", subject_GamePlace0.toString());
      assertEquals(1002, int0);
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.calcDaysInMonth(1, 1);
      assertEquals(31, int0);
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      Subject.StringAlgorithms.enlarge(0, byteArray0, 0);
      assertArrayEquals(new byte[] {}, byteArray0);
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(5);
      subject_GameConfiguration0.clearInitialBoard();
      assertEquals(5, subject_GameConfiguration0.getSize());
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(9);
      boolean boolean0 = subject_GameConfiguration0.isBoardFull();
      assertFalse(boolean0);
      assertEquals(9, subject_GameConfiguration0.getSize());
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(5);
      subject_GameConfiguration0.getPlacesOfPlayer(subject_GamePlayer0);
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
      assertEquals(5, subject_GameConfiguration0.getSize());
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(23);
      boolean boolean0 = subject_GameConfiguration0.isBoardSymmetric();
      assertTrue(boolean0);
      assertEquals(23, subject_GameConfiguration0.getSize());
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(5);
      int[] intArray0 = subject_GameConfiguration0.countPiecesPerPlayer();
      assertEquals(2, intArray0.length);
      assertEquals(5, subject_GameConfiguration0.getSize());
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(4, 7);
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertEquals(7, subject_GamePlace0.y());
      assertEquals(4, subject_GamePlace0.x());
      assertTrue(boolean0);
      assertEquals(7, subject_GameConfiguration0.getSize());
      assertEquals("(4, 7)", subject_GamePlace0.toString());
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 0);
      subject_GamePlace0.y((-577));
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertEquals("(0, -577)", subject_GamePlace0.toString());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(7);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(7, 7);
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertTrue(boolean0);
      assertEquals(7, subject_GameConfiguration0.getSize());
      assertEquals(7, subject_GamePlace0.y());
      assertEquals(7, subject_GamePlace0.x());
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, 0);
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertEquals(0, subject_GamePlace0.y());
      assertEquals(0, subject_GamePlace0.x());
      assertEquals(3, subject_GameConfiguration0.getSize());
      assertEquals("(0, 0)", subject_GamePlace0.toString());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(23);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-19), 1);
      boolean boolean0 = subject_GameConfiguration0.isOccupied(subject_GamePlace0);
      assertTrue(boolean0);
      assertEquals(23, subject_GameConfiguration0.getSize());
      assertEquals((-19), subject_GamePlace0.x());
      assertEquals("(-19, 1)", subject_GamePlace0.toString());
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(5);
      String string0 = subject_GameConfiguration0.toString();
      assertEquals("GameConfiguration (size=5)\n. . . . .\n. . . . .\n. . . . .\n. . . . .\n. . . . .\n", string0);
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(25);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(2, 25);
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Place is out of bounds
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(3);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(0, (-2641));
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Place is out of bounds
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(9);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(9, 9);
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Place is out of bounds
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(11);
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-2897), 11);
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.getPlayerAt(subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Place is out of bounds
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(9);
      Subject.GamePlayer[][] subject_GamePlayerArray0 = subject_GameConfiguration0.getInitialBoard();
      assertEquals(9, subject_GamePlayerArray0.length);
      assertEquals(9, subject_GameConfiguration0.getSize());
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(19);
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(19, 19);
      // Undeclared exception!
      try { 
        subject_GameConfiguration0.addInitialPiece(subject_GamePlayer0, subject_GamePlace0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // the player of the piece is unknown
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[4];
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(23, subject_GamePlayerArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // there must be exactly two players
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer[] subject_GamePlayerArray0 = new Subject.GamePlayer[7];
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(813, subject_GamePlayerArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // size of gameboard is at most 25
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration(12);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // size of gameboard must be an odd number
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = null;
      try {
        subject_GameConfiguration0 = subject0.new GameConfiguration((-2718));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // size of gameboard must be at least 3
         //
         verifyException("comp5111.assignment.cut.Subject$GameConfiguration", e);
      }
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-10), 2742);
      int int0 = subject_GamePlace0.manhattanDistance((Subject.GamePlace) null);
      assertEquals("(-10, 2742)", subject_GamePlace0.toString());
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(1, 0);
      Subject.GamePlace subject_GamePlace1 = subject0.new GamePlace(1, 1);
      boolean boolean0 = subject_GamePlace0.isAdjacent(subject_GamePlace1);
      assertEquals("(1, 1)", subject_GamePlace1.toString());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(2710, 2710);
      boolean boolean0 = subject_GamePlace0.isAdjacent((Subject.GamePlace) null);
      assertEquals("(2710, 2710)", subject_GamePlace0.toString());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(31, 31);
      Subject.GamePlace subject_GamePlace1 = subject0.new GamePlace(31, 1);
      boolean boolean0 = subject_GamePlace1.equals(subject_GamePlace0);
      assertEquals("(31, 1)", subject_GamePlace1.toString());
      assertFalse(subject_GamePlace0.equals((Object)subject_GamePlace1));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-101302124), 2219);
      Subject.GamePlace subject_GamePlace1 = subject0.new GamePlace(108, 108);
      boolean boolean0 = subject_GamePlace0.equals(subject_GamePlace1);
      assertEquals("(-101302124, 2219)", subject_GamePlace0.toString());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-1), (-1));
      Subject.GamePlace subject_GamePlace1 = subject_GamePlace0.clone();
      boolean boolean0 = subject_GamePlace0.equals(subject_GamePlace1);
      assertTrue(boolean0);
      assertNotSame(subject_GamePlace1, subject_GamePlace0);
      assertEquals("(-1, -1)", subject_GamePlace0.toString());
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-2147458295), 'Y');
      boolean boolean0 = subject_GamePlace0.equals((Object) null);
      assertFalse(boolean0);
      assertEquals("(-2147458295, 89)", subject_GamePlace0.toString());
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(25, (-406));
      boolean boolean0 = subject_GamePlace0.equals(subject_GamePlace0);
      assertTrue(boolean0);
      assertEquals("(25, -406)", subject_GamePlace0.toString());
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace((-2), 0);
      Object object0 = new Object();
      boolean boolean0 = subject_GamePlace0.equals(object0);
      assertFalse(boolean0);
      assertEquals("(-2, 0)", subject_GamePlace0.toString());
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      Subject.GamePlayer subject_GamePlayer1 = subject_GamePlayer0.clone();
      subject_GamePlayer1.equals(subject_GamePlayer0);
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer1.toString());
      assertNotSame(subject_GamePlayer1, subject_GamePlayer0);
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      boolean boolean0 = subject_GamePlayer0.equals((Object) null);
      assertFalse(boolean0);
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      Object object0 = new Object();
      boolean boolean0 = subject_GamePlayer0.equals(object0);
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monthsBetween(1, 1, (-1293), 97);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monthsBetween((-1085), 10, 10, 0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monthsBetween(3377, 3377, 3377, 3377);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monthsBetween((-8), (-8), (-8), (-8));
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.lastDayOfMonth((-333), 11);
      assertEquals("-333-11-30", string0);
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.firstDayOfMonth(813, 12);
      assertEquals("0813-12-01", string0);
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.firstDayOfMonth((-406), 1296);
      assertEquals("(invalid)", string0);
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.firstDayOfMonth(101, (-19));
      assertEquals("(invalid)", string0);
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      List<String> list0 = Subject.DateTimeAlgorithms.listDatesBetween(2351, 2, 13, 13, 2, 13);
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.formatFullDate(1473, 1473, 1473);
      assertEquals("(invalid)", string0);
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDateStrings("0011-11-30", "0011-11-30");
      assertEquals(Integer.MIN_VALUE, int0);
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDateStrings("--JTtUt3m\"j&l7')tE", "-0x-+-2]&urKs$Oa2");
      assertEquals(Integer.MIN_VALUE, int0);
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysBetweenDateStrings("Qn<", "Apr");
      assertEquals(Integer.MIN_VALUE, int0);
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.daysInYear(312);
      assertEquals(366, int0);
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr((-19));
      assertEquals("(invalid)", string0);
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(12);
      assertEquals("Dec", string0);
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(11);
      assertEquals("Nov", string0);
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(10);
      assertEquals("Oct", string0);
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(9);
      assertEquals("Sep", string0);
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.formatFullDate(8, 8, 8);
      assertEquals("8th Aug 8", string0);
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(7);
      assertEquals("Jul", string0);
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(5);
      assertEquals("May", string0);
  }

  @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(4);
      assertEquals("Apr", string0);
  }

  @Test(timeout = 4000)
  public void test105()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(3);
      assertEquals("Mar", string0);
  }

  @Test(timeout = 4000)
  public void test106()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(2);
      assertEquals("Feb", string0);
  }

  @Test(timeout = 4000)
  public void test107()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.month2MonAbbr(1);
      assertEquals("Jan", string0);
  }

  @Test(timeout = 4000)
  public void test108()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Dec");
      assertEquals(12, int0);
  }

  @Test(timeout = 4000)
  public void test109()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("7 M");
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test110()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Nov");
      assertEquals(11, int0);
  }

  @Test(timeout = 4000)
  public void test111()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Aug");
      assertEquals(8, int0);
  }

  @Test(timeout = 4000)
  public void test112()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Jul");
      assertEquals(7, int0);
  }

  @Test(timeout = 4000)
  public void test113()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Jun");
      assertEquals(6, int0);
  }

  @Test(timeout = 4000)
  public void test114()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("May");
      assertEquals(5, int0);
  }

  @Test(timeout = 4000)
  public void test115()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Apr");
      assertEquals(4, int0);
  }

  @Test(timeout = 4000)
  public void test116()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Oct");
      assertEquals(10, int0);
  }

  @Test(timeout = 4000)
  public void test117()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Feb");
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test118()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Jan");
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test119()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("-0xFeb");
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test120()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month("Mar");
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test121()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.monAbbr2month((String) null);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test122()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(7);
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test123()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(6);
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test124()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(12);
      assertEquals(4, int0);
  }

  @Test(timeout = 4000)
  public void test125()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(1875);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test126()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(1);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test127()  throws Throwable  {
      int int0 = Subject.DateTimeAlgorithms.getQuarter(0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test128()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr((-136585832));
      assertEquals("(invalid)", string0);
  }

  @Test(timeout = 4000)
  public void test129()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr(1473);
      assertEquals("(invalid)", string0);
  }

  @Test(timeout = 4000)
  public void test130()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr(11);
      assertEquals("11th", string0);
  }

  @Test(timeout = 4000)
  public void test131()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.dayStr(92);
      assertEquals("(invalid)", string0);
  }

  @Test(timeout = 4000)
  public void test132()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString((-541));
      assertEquals("-541 S", string0);
  }

  @Test(timeout = 4000)
  public void test133()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(3600L);
      assertEquals("1 H", string0);
  }

  @Test(timeout = 4000)
  public void test134()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(86400L);
      assertEquals("1 D", string0);
  }

  @Test(timeout = 4000)
  public void test135()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(604800L);
      assertEquals("1 W", string0);
  }

  @Test(timeout = 4000)
  public void test136()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(86400000L);
      assertEquals("3 Y", string0);
  }

  @Test(timeout = 4000)
  public void test137()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.roundSecondToString(2646);
      assertEquals("44 M", string0);
  }

  @Test(timeout = 4000)
  public void test138()  throws Throwable  {
      boolean boolean0 = Subject.DateTimeAlgorithms.judgeLeapYear((short)0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test139()  throws Throwable  {
      boolean boolean0 = Subject.DateTimeAlgorithms.judgeLeapYear((-100));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test140()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.DateTimeAlgorithms.daysBetweenDates(0, 9, 0, 1989, 13, (-1589));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid date
         //
         verifyException("comp5111.assignment.cut.Subject$DateTimeAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test141()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.formatFullDate(6, 6, 6);
      assertEquals("6th Jun 6", string0);
  }

  @Test(timeout = 4000)
  public void test142()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.DateTimeAlgorithms.daysBetweenDates(4, 4, 5071225, 5071225, 4, 5071225);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid date
         //
         verifyException("comp5111.assignment.cut.Subject$DateTimeAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test143()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.lastDayOfMonth((-19), 1911);
      assertEquals("(invalid)", string0);
  }

  @Test(timeout = 4000)
  public void test144()  throws Throwable  {
      String string0 = Subject.DateTimeAlgorithms.lastDayOfMonth((-19), (-19));
      assertEquals("(invalid)", string0);
  }

  @Test(timeout = 4000)
  public void test145()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.DateTimeAlgorithms.daysBetweenDates(2, 2, 2, 2, (-3), 2);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid date
         //
         verifyException("comp5111.assignment.cut.Subject$DateTimeAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test146()  throws Throwable  {
      String string0 = Subject.StringAlgorithms.padRight((String) null, (short) (-196), 'z');
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test147()  throws Throwable  {
      String string0 = Subject.StringAlgorithms.padLeft((String) null, (short)2, '');
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test148()  throws Throwable  {
      String string0 = Subject.StringAlgorithms.padLeft("3gaz?m^j_w", (short)0, 'Y');
      assertEquals("3gaz?m^j_w", string0);
  }

  @Test(timeout = 4000)
  public void test149()  throws Throwable  {
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo(".1");
      assertNull(intArray0);
  }

  @Test(timeout = 4000)
  public void test150()  throws Throwable  {
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo("");
      assertNull(intArray0);
  }

  @Test(timeout = 4000)
  public void test151()  throws Throwable  {
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo((String) null);
      assertNull(intArray0);
  }

  @Test(timeout = 4000)
  public void test152()  throws Throwable  {
      int int0 = Subject.StringAlgorithms.extractIntInStr("");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test153()  throws Throwable  {
      int[] intArray0 = Subject.StringAlgorithms.getVersionNo("1");
      assertNotNull(intArray0);
      assertArrayEquals(new int[] {1, 0, 0, 0}, intArray0);
  }

  @Test(timeout = 4000)
  public void test154()  throws Throwable  {
      int int0 = Subject.StringAlgorithms.extractIntInStr((String) null);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test155()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber(".1");
      assertEquals((short)0, number0.shortValue());
  }

  @Test(timeout = 4000)
  public void test156()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("}55 X4vZcM9AnX{eE6");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"}55 X4vZc\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test157()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("&^6Sa)n5i5ie,[]e9");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // Character & is neither a decimal digit number, decimal point, nor \"e\" notation exponential mark.
         //
         verifyException("java.math.BigDecimal", e);
      }
  }

  @Test(timeout = 4000)
  public void test158()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("@F\">UV(D");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // Character @ is neither a decimal digit number, decimal point, nor \"e\" notation exponential mark.
         //
         verifyException("java.math.BigDecimal", e);
      }
  }

  @Test(timeout = 4000)
  public void test159()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("%04d-%02d-%02d");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // Character % is neither a decimal digit number, decimal point, nor \"e\" notation exponential mark.
         //
         verifyException("java.math.BigDecimal", e);
      }
  }

  @Test(timeout = 4000)
  public void test160()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("3F");
      assertEquals(3.0F, number0);
  }

  @Test(timeout = 4000)
  public void test161()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("f?{),UMe:)@zFi&f");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
      }
  }

  @Test(timeout = 4000)
  public void test162()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("-!XS7r,Qdl");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // -!XS7r,Qdl
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test163()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("E!Jul");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // E!Jul
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test164()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("Invalid date");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // Invalid date
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test165()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("comp5111.assignment.cut.Subject$StringAlgorithms");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // comp5111.assignment.cut.Subject$StringAlgorithms
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test166()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("GameConfiguration (size=5)\n. . . . .\n. . . . .\n. . . . .\n. . . . .\n. . . . .\n");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // GameConfiguration (size=5)
         // . . . . .
         // . . . . .
         // . . . . .
         // . . . . .
         // . . . . .
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test167()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("uFz6sy;-~U\".+[P,l");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // uFz6sy;-~U\".+[P,l
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test168()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("-0x5WQO,g$Ki6|a+l");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"-5WQO,g$Ki6|a+l\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test169()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.parseNumber("0xAug");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"Aug\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test170()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("--'TNeK2");
      assertNull(number0);
  }

  @Test(timeout = 4000)
  public void test171()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("1");
      assertEquals((short)1, number0.shortValue());
  }

  @Test(timeout = 4000)
  public void test172()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("n");
      assertNull(number0);
  }

  @Test(timeout = 4000)
  public void test173()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("");
      assertNull(number0);
  }

  @Test(timeout = 4000)
  public void test174()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber((String) null);
      assertNull(number0);
  }

  @Test(timeout = 4000)
  public void test175()  throws Throwable  {
      Number number0 = Subject.StringAlgorithms.parseNumber("9L");
      assertEquals((short)9, number0.shortValue());
  }

  @Test(timeout = 4000)
  public void test176()  throws Throwable  {
      char[] charArray0 = new char[7];
      charArray0[0] = 'a';
      String string0 = Subject.StringAlgorithms.parseToken("Anonymous Player", charArray0);
      assertEquals("Anonymous Pla", string0);
  }

  @Test(timeout = 4000)
  public void test177()  throws Throwable  {
      char[] charArray0 = new char[3];
      String string0 = Subject.StringAlgorithms.parseToken("{", charArray0);
      assertEquals("{", string0);
  }

  @Test(timeout = 4000)
  public void test178()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.strToBoolean("-0x~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~", "0x", "0x", "0x");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test179()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("O", "P", "P", "O");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test180()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("1 S", "(invalid)", "1 S", "-19 S");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test181()  throws Throwable  {
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.strToBoolean((String) null, "P", "P", "P");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test182()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean((String) null, (String) null, (String) null, "-684 S");
      assertNotNull(boolean0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test183()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean((String) null, "L;fKRxp>:a!ht(r)Jb", "L;fKRxp>:a!ht(r)Jb", (String) null);
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test184()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean((String) null, "", (String) null, "");
      assertFalse(boolean0);
      assertNotNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test185()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("n", "n", "n", "O");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test186()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("0x-41");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test187()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("FLUnY");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test188()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("fB9;b");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test189()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("TYLM");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test190()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("44 M");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test191()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("YLM");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test192()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("y(2");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test193()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("Ofg");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test194()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("Oct");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test195()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("o9Y");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test196()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("OL");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test197()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("o]");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test198()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("nn");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test199()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("N6");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test200()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("F");
      assertNotNull(boolean0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test201()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("f");
      assertNotNull(boolean0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test202()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("N");
      assertNotNull(boolean0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test203()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("n");
      assertNotNull(boolean0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test204()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("T");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test205()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("t");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test206()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("Y");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test207()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("y");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test208()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean((String) null);
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test209()  throws Throwable  {
      Boolean boolean0 = Subject.StringAlgorithms.strToBoolean("tf;b");
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test210()  throws Throwable  {
      byte[] byteArray0 = new byte[5];
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.enlarge((-645), byteArray0, (byte) (-57));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test211()  throws Throwable  {
      byte[] byteArray0 = new byte[2];
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.enlarge(4402, byteArray0, 2656);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test212()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      byteArray0[0] = (byte) (-127);
      ByteBuffer byteBuffer0 = ByteBuffer.wrap(byteArray0);
      StringBuilder stringBuilder0 = new StringBuilder((CharSequence) "(invalid)");
      int int0 = Subject.StringAlgorithms.decodeOctets((byte) (-127), byteBuffer0, stringBuilder0);
      assertEquals("(invalid)\uFFFD", stringBuilder0.toString());
      assertEquals((-125), int0);
  }

  @Test(timeout = 4000)
  public void test213()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      ByteBuffer byteBuffer0 = ByteBuffer.wrap(byteArray0);
      StringBuilder stringBuilder0 = new StringBuilder((CharSequence) "(invalid)");
      int int0 = Subject.StringAlgorithms.decodeOctets((byte)0, byteBuffer0, stringBuilder0);
      assertEquals(2, int0);
      assertEquals(0, byteBuffer0.position());
  }

  @Test(timeout = 4000)
  public void test214()  throws Throwable  {
      ByteBuffer byteBuffer0 = ByteBuffer.allocateDirect(1443);
      // Undeclared exception!
      try { 
        Subject.StringAlgorithms.decodeOctets(1443, byteBuffer0, (StringBuilder) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("comp5111.assignment.cut.Subject$StringAlgorithms", e);
      }
  }

  @Test(timeout = 4000)
  public void test215()  throws Throwable  {
      String[] stringArray0 = new String[6];
      stringArray0[0] = "GameConfiguration (size=9)\n. . . . . . . . .\n. . . . . . . . .\n. . . . . . . . .\n. . . . . . . . .\n. . . . . . . . .\n. . . . . . . . .\n. . . . . . . . .\n. . . . . . . . .\n. . . . . . . . .\n";
      String[] stringArray1 = Subject.StringAlgorithms.trimArrayElements(stringArray0);
      assertEquals(6, stringArray1.length);
      assertNotSame(stringArray1, stringArray0);
  }

  @Test(timeout = 4000)
  public void test216()  throws Throwable  {
      String[] stringArray0 = new String[0];
      String[] stringArray1 = Subject.StringAlgorithms.trimArrayElements(stringArray0);
      assertEquals(0, stringArray1.length);
  }

  @Test(timeout = 4000)
  public void test217()  throws Throwable  {
      String[] stringArray0 = Subject.StringAlgorithms.trimArrayElements((String[]) null);
      assertEquals(0, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test218()  throws Throwable  {
      boolean boolean0 = Subject.StringAlgorithms.startsWithIgnoreCase("(invalid)", "(invalid)");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test219()  throws Throwable  {
      boolean boolean0 = Subject.StringAlgorithms.startsWithIgnoreCase("", "a\"xnrm.*v");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test220()  throws Throwable  {
      boolean boolean0 = Subject.StringAlgorithms.startsWithIgnoreCase("`,Nzs!'El0}kD", (String) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test221()  throws Throwable  {
      boolean boolean0 = Subject.StringAlgorithms.startsWithIgnoreCase("Dec", "W");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test222()  throws Throwable  {
      boolean boolean0 = Subject.StringAlgorithms.startsWithIgnoreCase((String) null, (String) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test223()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("kh]g[}>~");
      subject_GamePlayer0.addScore(0);
      assertEquals("GamePlayer{name='kh]g[}>~', score=0}", subject_GamePlayer0.toString());
  }

  @Test(timeout = 4000)
  public void test224()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      subject_GamePlayer0.resetScore();
      assertEquals("GamePlayer{name='Anonymous Player', score=0}", subject_GamePlayer0.toString());
  }

  @Test(timeout = 4000)
  public void test225()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      String string0 = subject_GamePlayer0.getName();
      assertEquals("Anonymous Player", string0);
  }

  @Test(timeout = 4000)
  public void test226()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer("-0xSjE8$_,bg?]Y;");
      subject_GamePlayer0.setScore((-3126));
      assertEquals("GamePlayer{name='-0xSjE8$_,bg?]Y;', score=-3126}", subject_GamePlayer0.toString());
  }

  @Test(timeout = 4000)
  public void test227()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer();
      int int0 = subject_GamePlayer0.getScore();
      assertEquals(0, int0);
      assertEquals("Anonymous Player", subject_GamePlayer0.getName());
  }

  @Test(timeout = 4000)
  public void test228()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlayer subject_GamePlayer0 = subject0.new GamePlayer((String) null);
      String string0 = subject_GamePlayer0.toString();
      assertEquals("GamePlayer{name='null', score=0}", string0);
  }

  @Test(timeout = 4000)
  public void test229()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(9);
      int int0 = subject_GameConfiguration0.getSize();
      assertEquals(9, int0);
  }

  @Test(timeout = 4000)
  public void test230()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(11);
      subject_GameConfiguration0.getPlayers();
      assertEquals(11, subject_GameConfiguration0.getSize());
  }

  @Test(timeout = 4000)
  public void test231()  throws Throwable  {
      Subject.StringAlgorithms subject_StringAlgorithms0 = new Subject.StringAlgorithms();
  }

  @Test(timeout = 4000)
  public void test232()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(5);
      Subject.GameConfiguration subject_GameConfiguration1 = subject_GameConfiguration0.clone();
      assertNotSame(subject_GameConfiguration1, subject_GameConfiguration0);
      assertEquals(5, subject_GameConfiguration1.getSize());
  }

  @Test(timeout = 4000)
  public void test233()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GameConfiguration subject_GameConfiguration0 = subject0.new GameConfiguration(5);
      List<Subject.GamePlace> list0 = subject_GameConfiguration0.getEmptyPlaces();
      assertEquals(24, list0.size());
  }

  @Test(timeout = 4000)
  public void test234()  throws Throwable  {
      Subject subject0 = new Subject();
      Subject.GamePlace subject_GamePlace0 = subject0.new GamePlace(14, 14);
      String string0 = subject_GamePlace0.toString();
      assertEquals("(14, 14)", string0);
  }

  @Test(timeout = 4000)
  public void test235()  throws Throwable  {
      Subject.DateTimeAlgorithms subject_DateTimeAlgorithms0 = new Subject.DateTimeAlgorithms();
  }
}
